// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activatePartnerDraftLocations = `-- name: ActivatePartnerDraftLocations :execrows
UPDATE locations
SET status = 'active',
    updated_at = NOW()
WHERE partner_id = $1
  AND status = 'draft'
`

func (q *Queries) ActivatePartnerDraftLocations(ctx context.Context, partnerID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, activatePartnerDraftLocations, partnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activatePartnerIfPendingDocuments = `-- name: ActivatePartnerIfPendingDocuments :one
UPDATE partners
SET status = CASE WHEN status = 'pending_documents' THEN 'active' ELSE status END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at
`

func (q *Queries) ActivatePartnerIfPendingDocuments(ctx context.Context, id uuid.UUID) (Partner, error) {
	row := q.db.QueryRow(ctx, activatePartnerIfPendingDocuments, id)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAdminApplications = `-- name: CountAdminApplications :one
SELECT COUNT(*)
FROM partner_applications
WHERE (
    $1::text = ''
    OR status = $1::text
)
AND (
    $2::text = ''
    OR contact_name ILIKE '%' || $2::text || '%'
    OR contact_email ILIKE '%' || $2::text || '%'
    OR contact_phone ILIKE '%' || $2::text || '%'
    OR business_name ILIKE '%' || $2::text || '%'
    OR address ILIKE '%' || $2::text || '%'
)
`

type CountAdminApplicationsParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
}

func (q *Queries) CountAdminApplications(ctx context.Context, arg CountAdminApplicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminApplications, arg.StatusFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminAuditLog = `-- name: CountAdminAuditLog :one
SELECT COUNT(*)
FROM admin_audit_log al
WHERE (
    $1::text = ''
    OR al.action = $1::text
)
AND (
    $2::text = ''
    OR al.entity_type = $2::text
)
`

type CountAdminAuditLogParams struct {
	ActionFilter     string `json:"action_filter"`
	EntityTypeFilter string `json:"entity_type_filter"`
}

func (q *Queries) CountAdminAuditLog(ctx context.Context, arg CountAdminAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAuditLog, arg.ActionFilter, arg.EntityTypeFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminBoxes = `-- name: CountAdminBoxes :one
SELECT COUNT(*)
FROM surprise_boxes sb
JOIN locations l ON l.id = sb.location_id
JOIN partners p ON p.id = l.partner_id
WHERE (
    $1::text = ''
    OR sb.status = $1::text
)
AND (
    $2::text = ''
    OR sb.location_id = $2::uuid
)
AND (
    $3::text = ''
    OR sb.name ILIKE '%' || $3::text || '%'
    OR l.name ILIKE '%' || $3::text || '%'
    OR p.brand_name ILIKE '%' || $3::text || '%'
)
`

type CountAdminBoxesParams struct {
	StatusFilter     string `json:"status_filter"`
	LocationIDFilter string `json:"location_id_filter"`
	Search           string `json:"search"`
}

func (q *Queries) CountAdminBoxes(ctx context.Context, arg CountAdminBoxesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminBoxes, arg.StatusFilter, arg.LocationIDFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminCustomers = `-- name: CountAdminCustomers :one
SELECT COUNT(*)
FROM users u
WHERE (
    $1::text = ''
    OR u.phone ILIKE '%' || $1::text || '%'
    OR u.name ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountAdminCustomers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminCustomers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminLocations = `-- name: CountAdminLocations :one
SELECT COUNT(*)
FROM locations l
JOIN partners p ON p.id = l.partner_id
WHERE (
    $1::text = ''
    OR l.status = $1::text
)
AND (
    $2::text = ''
    OR l.partner_id = $2::uuid
)
AND (
    $3::text = ''
    OR l.name ILIKE '%' || $3::text || '%'
    OR l.address ILIKE '%' || $3::text || '%'
    OR p.brand_name ILIKE '%' || $3::text || '%'
)
`

type CountAdminLocationsParams struct {
	StatusFilter    string `json:"status_filter"`
	PartnerIDFilter string `json:"partner_id_filter"`
	Search          string `json:"search"`
}

func (q *Queries) CountAdminLocations(ctx context.Context, arg CountAdminLocationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminLocations, arg.StatusFilter, arg.PartnerIDFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminOrders = `-- name: CountAdminOrders :one
SELECT COUNT(*)
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN surprise_boxes sb ON sb.id = o.box_id
JOIN locations l ON l.id = o.location_id
JOIN partners p ON p.id = l.partner_id
WHERE (
    $1::text = ''
    OR o.status::text = $1::text
)
AND (
    $2::text = ''
    OR o.pickup_code ILIKE '%' || $2::text || '%'
    OR u.phone ILIKE '%' || $2::text || '%'
    OR sb.name ILIKE '%' || $2::text || '%'
    OR l.name ILIKE '%' || $2::text || '%'
    OR p.brand_name ILIKE '%' || $2::text || '%'
)
`

type CountAdminOrdersParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
}

func (q *Queries) CountAdminOrders(ctx context.Context, arg CountAdminOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminOrders, arg.StatusFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminPartners = `-- name: CountAdminPartners :one
SELECT COUNT(DISTINCT p.id)
FROM partners p
LEFT JOIN partner_legal_info pli ON pli.partner_id = p.id
WHERE (
    $1::text = ''
    OR p.status = $1::text
)
AND (
    $2::text = ''
    OR p.brand_name ILIKE '%' || $2::text || '%'
    OR pli.legal_name ILIKE '%' || $2::text || '%'
)
AND (
    $3::text = ''
    OR COALESCE(pli.verification_status, '') = $3::text
)
`

type CountAdminPartnersParams struct {
	StatusFilter      string `json:"status_filter"`
	Search            string `json:"search"`
	LegalStatusFilter string `json:"legal_status_filter"`
}

func (q *Queries) CountAdminPartners(ctx context.Context, arg CountAdminPartnersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminPartners, arg.StatusFilter, arg.Search, arg.LegalStatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminPaymentEvents = `-- name: CountAdminPaymentEvents :one
SELECT COUNT(*)
FROM payment_events
WHERE payment_id = $1
`

func (q *Queries) CountAdminPaymentEvents(ctx context.Context, paymentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminPaymentEvents, paymentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminPayments = `-- name: CountAdminPayments :one
SELECT COUNT(*)
FROM payments pay
JOIN orders o ON o.id = pay.order_id
JOIN users u ON u.id = o.user_id
WHERE (
    $1::text = ''
    OR pay.status::text = $1::text
)
AND (
    $2::text = ''
    OR pay.provider_payment_id ILIKE '%' || $2::text || '%'
    OR o.pickup_code ILIKE '%' || $2::text || '%'
    OR u.phone ILIKE '%' || $2::text || '%'
)
`

type CountAdminPaymentsParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
}

func (q *Queries) CountAdminPayments(ctx context.Context, arg CountAdminPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminPayments, arg.StatusFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)
FROM admin_users
WHERE (
    $1::text = ''
    OR email ILIKE '%' || $1::text || '%'
    OR name ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountAdminUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_log (
    admin_user_id,
    action,
    entity_type,
    entity_id,
    details,
    ip_address
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, admin_user_id, action, entity_type, entity_id, details, ip_address, created_at
`

type CreateAdminAuditLogParams struct {
	AdminUserID uuid.UUID   `json:"admin_user_id"`
	Action      string      `json:"action"`
	EntityType  pgtype.Text `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Details     []byte      `json:"details"`
	IpAddress   *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.AdminUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    email,
    password_hash,
    name,
    role,
    is_active
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, name, role, is_active, last_login_at, created_at, updated_at
`

type CreateAdminUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.IsActive,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAdminUser = `-- name: DeactivateAdminUser :execrows
UPDATE admin_users
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
  AND is_active = TRUE
`

func (q *Queries) DeactivateAdminUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAdminUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAdminByEmail = `-- name: FindAdminByEmail :one
SELECT id, email, password_hash, name, role, is_active, last_login_at, created_at, updated_at
FROM admin_users
WHERE email = $1
`

func (q *Queries) FindAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAdminByID = `-- name: FindAdminByID :one
SELECT id, email, password_hash, name, role, is_active, last_login_at, created_at, updated_at
FROM admin_users
WHERE id = $1
`

func (q *Queries) FindAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPartnerOwnerForNotification = `-- name: FindPartnerOwnerForNotification :one
SELECT email, name
FROM partner_employees
WHERE partner_id = $1
  AND role = 'owner'
ORDER BY created_at ASC
LIMIT 1
`

type FindPartnerOwnerForNotificationRow struct {
	Email string      `json:"email"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) FindPartnerOwnerForNotification(ctx context.Context, partnerID uuid.UUID) (FindPartnerOwnerForNotificationRow, error) {
	row := q.db.QueryRow(ctx, findPartnerOwnerForNotification, partnerID)
	var i FindPartnerOwnerForNotificationRow
	err := row.Scan(&i.Email, &i.Name)
	return i, err
}

const getAdminBoxByID = `-- name: GetAdminBoxByID :one
SELECT sb.id,
       sb.location_id,
       l.name AS location_name,
       l.partner_id,
       p.brand_name AS partner_name,
       sb.name,
       COALESCE(sb.description, '') AS description,
       sb.original_price,
       sb.discount_price,
       sb.quantity_available,
       sb.pickup_time_start,
       sb.pickup_time_end,
       COALESCE(sb.image_url, '') AS image_url,
       sb.status,
       sb.created_at,
       sb.updated_at,
       COUNT(o.id)::int AS total_orders
FROM surprise_boxes sb
JOIN locations l ON l.id = sb.location_id
JOIN partners p ON p.id = l.partner_id
LEFT JOIN orders o ON o.box_id = sb.id
WHERE sb.id = $1
GROUP BY sb.id, l.id, p.id
`

type GetAdminBoxByIDRow struct {
	ID                uuid.UUID      `json:"id"`
	LocationID        uuid.UUID      `json:"location_id"`
	LocationName      string         `json:"location_name"`
	PartnerID         uuid.UUID      `json:"partner_id"`
	PartnerName       string         `json:"partner_name"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	OriginalPrice     pgtype.Numeric `json:"original_price"`
	DiscountPrice     pgtype.Numeric `json:"discount_price"`
	QuantityAvailable int32          `json:"quantity_available"`
	PickupTimeStart   pgtype.Time    `json:"pickup_time_start"`
	PickupTimeEnd     pgtype.Time    `json:"pickup_time_end"`
	ImageUrl          string         `json:"image_url"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	TotalOrders       int32          `json:"total_orders"`
}

func (q *Queries) GetAdminBoxByID(ctx context.Context, id uuid.UUID) (GetAdminBoxByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminBoxByID, id)
	var i GetAdminBoxByIDRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.LocationName,
		&i.PartnerID,
		&i.PartnerName,
		&i.Name,
		&i.Description,
		&i.OriginalPrice,
		&i.DiscountPrice,
		&i.QuantityAvailable,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalOrders,
	)
	return i, err
}

const getAdminCustomerByID = `-- name: GetAdminCustomerByID :one
SELECT u.id,
       u.phone,
       u.name,
       u.created_at,
       u.updated_at,
       COUNT(o.id)::int AS total_orders,
       COALESCE(SUM(o.amount) FILTER (WHERE o.status IN ('completed', 'picked_up')), 0)::numeric AS total_spent
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.id = $1
GROUP BY u.id
`

type GetAdminCustomerByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Phone       string         `json:"phone"`
	Name        pgtype.Text    `json:"name"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	TotalOrders int32          `json:"total_orders"`
	TotalSpent  pgtype.Numeric `json:"total_spent"`
}

func (q *Queries) GetAdminCustomerByID(ctx context.Context, id uuid.UUID) (GetAdminCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminCustomerByID, id)
	var i GetAdminCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalOrders,
		&i.TotalSpent,
	)
	return i, err
}

const getAdminLocationByID = `-- name: GetAdminLocationByID :one
SELECT l.id,
       l.partner_id,
       p.brand_name AS partner_name,
       l.category_code,
       l.name,
       l.address,
       COALESCE(l.phone, '') AS phone,
       COALESCE(l.logo_url, '') AS logo_url,
       COALESCE(l.cover_image_url, '') AS cover_image_url,
       l.gallery_urls,
       l.working_hours,
       l.status,
       l.created_at,
       l.updated_at,
       COUNT(DISTINCT sb.id)::int AS boxes_count,
       COUNT(DISTINCT o.id)::int AS total_orders
FROM locations l
JOIN partners p ON p.id = l.partner_id
LEFT JOIN surprise_boxes sb ON sb.location_id = l.id
LEFT JOIN orders o ON o.location_id = l.id
WHERE l.id = $1
GROUP BY l.id, p.brand_name
`

type GetAdminLocationByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	PartnerID     uuid.UUID        `json:"partner_id"`
	PartnerName   string           `json:"partner_name"`
	CategoryCode  string           `json:"category_code"`
	Name          string           `json:"name"`
	Address       string           `json:"address"`
	Phone         string           `json:"phone"`
	LogoUrl       string           `json:"logo_url"`
	CoverImageUrl string           `json:"cover_image_url"`
	GalleryUrls   []string         `json:"gallery_urls"`
	WorkingHours  []byte           `json:"working_hours"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	BoxesCount    int32            `json:"boxes_count"`
	TotalOrders   int32            `json:"total_orders"`
}

func (q *Queries) GetAdminLocationByID(ctx context.Context, id uuid.UUID) (GetAdminLocationByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminLocationByID, id)
	var i GetAdminLocationByIDRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.PartnerName,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoxesCount,
		&i.TotalOrders,
	)
	return i, err
}

const getAdminOrderByID = `-- name: GetAdminOrderByID :one
SELECT o.id, o.user_id, o.box_id, o.location_id, o.pickup_code, o.qr_code_url, o.amount, o.pickup_time_start, o.pickup_time_end, o.status, o.partner_confirmation_deadline, o.partner_confirmed_at, o.partner_confirmed_by, o.cancellation_reason, o.cancelled_at, o.picked_up_at, o.picked_up_confirmed_by, o.user_confirmed_at, o.auto_completed_at, o.created_at, o.updated_at,
       u.phone AS customer_phone,
       COALESCE(u.name, '') AS customer_name,
       sb.name AS box_name,
       l.name AS location_name,
       l.address AS location_address,
       l.partner_id,
       p.brand_name AS partner_name
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN surprise_boxes sb ON sb.id = o.box_id
JOIN locations l ON l.id = o.location_id
JOIN partners p ON p.id = l.partner_id
WHERE o.id = $1
`

type GetAdminOrderByIDRow struct {
	ID                          uuid.UUID          `json:"id"`
	UserID                      uuid.UUID          `json:"user_id"`
	BoxID                       uuid.UUID          `json:"box_id"`
	LocationID                  uuid.UUID          `json:"location_id"`
	PickupCode                  string             `json:"pickup_code"`
	QrCodeUrl                   pgtype.Text        `json:"qr_code_url"`
	Amount                      pgtype.Numeric     `json:"amount"`
	PickupTimeStart             time.Time          `json:"pickup_time_start"`
	PickupTimeEnd               time.Time          `json:"pickup_time_end"`
	Status                      OrderStatus        `json:"status"`
	PartnerConfirmationDeadline time.Time          `json:"partner_confirmation_deadline"`
	PartnerConfirmedAt          pgtype.Timestamptz `json:"partner_confirmed_at"`
	PartnerConfirmedBy          pgtype.UUID        `json:"partner_confirmed_by"`
	CancellationReason          pgtype.Text        `json:"cancellation_reason"`
	CancelledAt                 pgtype.Timestamptz `json:"cancelled_at"`
	PickedUpAt                  pgtype.Timestamptz `json:"picked_up_at"`
	PickedUpConfirmedBy         pgtype.UUID        `json:"picked_up_confirmed_by"`
	UserConfirmedAt             pgtype.Timestamptz `json:"user_confirmed_at"`
	AutoCompletedAt             pgtype.Timestamptz `json:"auto_completed_at"`
	CreatedAt                   time.Time          `json:"created_at"`
	UpdatedAt                   time.Time          `json:"updated_at"`
	CustomerPhone               string             `json:"customer_phone"`
	CustomerName                string             `json:"customer_name"`
	BoxName                     string             `json:"box_name"`
	LocationName                string             `json:"location_name"`
	LocationAddress             string             `json:"location_address"`
	PartnerID                   uuid.UUID          `json:"partner_id"`
	PartnerName                 string             `json:"partner_name"`
}

func (q *Queries) GetAdminOrderByID(ctx context.Context, id uuid.UUID) (GetAdminOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminOrderByID, id)
	var i GetAdminOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoxID,
		&i.LocationID,
		&i.PickupCode,
		&i.QrCodeUrl,
		&i.Amount,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.Status,
		&i.PartnerConfirmationDeadline,
		&i.PartnerConfirmedAt,
		&i.PartnerConfirmedBy,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.PickedUpAt,
		&i.PickedUpConfirmedBy,
		&i.UserConfirmedAt,
		&i.AutoCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerPhone,
		&i.CustomerName,
		&i.BoxName,
		&i.LocationName,
		&i.LocationAddress,
		&i.PartnerID,
		&i.PartnerName,
	)
	return i, err
}

const getAdminPartnerByID = `-- name: GetAdminPartnerByID :one
SELECT p.id,
       p.brand_name,
       COALESCE(pli.legal_name, '') AS legal_name,
       p.logo_url,
       p.parent_partner_id,
       p.account_type,
       p.commission_rate,
       p.promo_commission_rate,
       p.promo_commission_until,
       p.status,
       p.created_at,
       p.updated_at,
       COALESCE(pli.inn, '') AS inn,
       COALESCE(pli.ogrn, '') AS ogrn,
       COALESCE(pli.kpp, '') AS kpp,
       COALESCE(pli.legal_address, '') AS legal_address,
       COALESCE(pli.verification_status, '') AS legal_verification_status,
       COALESCE(pli.verification_comment, '') AS legal_verification_comment,
       pli.verified_by,
       pli.verified_at,
       COUNT(DISTINCT l.id)::int AS locations_count,
       COUNT(DISTINCT o.id)::int AS total_orders,
       COALESCE(SUM(o.amount) FILTER (WHERE o.status IN ('completed', 'picked_up')), 0)::numeric AS total_revenue
FROM partners p
LEFT JOIN partner_legal_info pli ON pli.partner_id = p.id
LEFT JOIN locations l ON l.partner_id = p.id
LEFT JOIN orders o ON o.location_id = l.id
WHERE p.id = $1
GROUP BY p.id, pli.partner_id
`

type GetAdminPartnerByIDRow struct {
	ID                       uuid.UUID        `json:"id"`
	BrandName                string           `json:"brand_name"`
	LegalName                string           `json:"legal_name"`
	LogoUrl                  pgtype.Text      `json:"logo_url"`
	ParentPartnerID          pgtype.UUID      `json:"parent_partner_id"`
	AccountType              pgtype.Text      `json:"account_type"`
	CommissionRate           pgtype.Numeric   `json:"commission_rate"`
	PromoCommissionRate      pgtype.Numeric   `json:"promo_commission_rate"`
	PromoCommissionUntil     pgtype.Date      `json:"promo_commission_until"`
	Status                   string           `json:"status"`
	CreatedAt                time.Time        `json:"created_at"`
	UpdatedAt                time.Time        `json:"updated_at"`
	Inn                      string           `json:"inn"`
	Ogrn                     string           `json:"ogrn"`
	Kpp                      string           `json:"kpp"`
	LegalAddress             string           `json:"legal_address"`
	LegalVerificationStatus  string           `json:"legal_verification_status"`
	LegalVerificationComment string           `json:"legal_verification_comment"`
	VerifiedBy               pgtype.UUID      `json:"verified_by"`
	VerifiedAt               pgtype.Timestamp `json:"verified_at"`
	LocationsCount           int32            `json:"locations_count"`
	TotalOrders              int32            `json:"total_orders"`
	TotalRevenue             pgtype.Numeric   `json:"total_revenue"`
}

func (q *Queries) GetAdminPartnerByID(ctx context.Context, id uuid.UUID) (GetAdminPartnerByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminPartnerByID, id)
	var i GetAdminPartnerByIDRow
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LegalName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inn,
		&i.Ogrn,
		&i.Kpp,
		&i.LegalAddress,
		&i.LegalVerificationStatus,
		&i.LegalVerificationComment,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.LocationsCount,
		&i.TotalOrders,
		&i.TotalRevenue,
	)
	return i, err
}

const getAdminPaymentByID = `-- name: GetAdminPaymentByID :one
SELECT pay.id, pay.order_id, pay.provider_payment_id, pay.payment_url, pay.method, pay.provider, pay.amount, pay.status, pay.paid_at, pay.created_at, pay.updated_at,
       o.pickup_code,
       u.phone AS customer_phone,
       l.name AS location_name,
       p.brand_name AS partner_name
FROM payments pay
JOIN orders o ON o.id = pay.order_id
JOIN users u ON u.id = o.user_id
JOIN locations l ON l.id = o.location_id
JOIN partners p ON p.id = l.partner_id
WHERE pay.id = $1
`

type GetAdminPaymentByIDRow struct {
	ID                uuid.UUID           `json:"id"`
	OrderID           uuid.UUID           `json:"order_id"`
	ProviderPaymentID pgtype.Text         `json:"provider_payment_id"`
	PaymentUrl        pgtype.Text         `json:"payment_url"`
	Method            NullPaymentMethod   `json:"method"`
	Provider          NullPaymentProvider `json:"provider"`
	Amount            pgtype.Numeric      `json:"amount"`
	Status            PaymentStatus       `json:"status"`
	PaidAt            pgtype.Timestamptz  `json:"paid_at"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	PickupCode        string              `json:"pickup_code"`
	CustomerPhone     string              `json:"customer_phone"`
	LocationName      string              `json:"location_name"`
	PartnerName       string              `json:"partner_name"`
}

func (q *Queries) GetAdminPaymentByID(ctx context.Context, id uuid.UUID) (GetAdminPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminPaymentByID, id)
	var i GetAdminPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Method,
		&i.Provider,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickupCode,
		&i.CustomerPhone,
		&i.LocationName,
		&i.PartnerName,
	)
	return i, err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT (SELECT COUNT(*) FROM users)::int AS customers_total,
       (SELECT COUNT(*) FROM partners)::int AS partners_total,
       (SELECT COUNT(*) FROM partners WHERE status = 'active')::int AS partners_active,
       (SELECT COUNT(*) FROM locations)::int AS locations_total,
       (SELECT COUNT(*) FROM surprise_boxes)::int AS boxes_total,
       (SELECT COUNT(*) FROM orders)::int AS orders_total,
       (SELECT COUNT(*) FROM orders WHERE status = 'completed')::int AS orders_completed,
       (SELECT COUNT(*) FROM orders WHERE status = 'cancelled')::int AS orders_cancelled,
       (SELECT COUNT(*) FROM orders WHERE status = 'disputed')::int AS orders_disputed,
       (SELECT COALESCE(SUM(amount), 0)::numeric FROM orders WHERE status IN ('completed', 'picked_up')) AS gross_revenue,
       (SELECT COUNT(*) FROM payments)::int AS payments_total,
       (SELECT COUNT(*) FROM payments WHERE status = 'succeeded')::int AS payments_succeeded
`

type GetAdminStatsRow struct {
	CustomersTotal    int32          `json:"customers_total"`
	PartnersTotal     int32          `json:"partners_total"`
	PartnersActive    int32          `json:"partners_active"`
	LocationsTotal    int32          `json:"locations_total"`
	BoxesTotal        int32          `json:"boxes_total"`
	OrdersTotal       int32          `json:"orders_total"`
	OrdersCompleted   int32          `json:"orders_completed"`
	OrdersCancelled   int32          `json:"orders_cancelled"`
	OrdersDisputed    int32          `json:"orders_disputed"`
	GrossRevenue      pgtype.Numeric `json:"gross_revenue"`
	PaymentsTotal     int32          `json:"payments_total"`
	PaymentsSucceeded int32          `json:"payments_succeeded"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.CustomersTotal,
		&i.PartnersTotal,
		&i.PartnersActive,
		&i.LocationsTotal,
		&i.BoxesTotal,
		&i.OrdersTotal,
		&i.OrdersCompleted,
		&i.OrdersCancelled,
		&i.OrdersDisputed,
		&i.GrossRevenue,
		&i.PaymentsTotal,
		&i.PaymentsSucceeded,
	)
	return i, err
}

const listAdminApplications = `-- name: ListAdminApplications :many
SELECT id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude, reviewed_by
FROM partner_applications
WHERE (
    $1::text = ''
    OR status = $1::text
)
AND (
    $2::text = ''
    OR contact_name ILIKE '%' || $2::text || '%'
    OR contact_email ILIKE '%' || $2::text || '%'
    OR contact_phone ILIKE '%' || $2::text || '%'
    OR business_name ILIKE '%' || $2::text || '%'
    OR address ILIKE '%' || $2::text || '%'
)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminApplicationsParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageOffset   int32  `json:"page_offset"`
	PageLimit    int32  `json:"page_limit"`
}

func (q *Queries) ListAdminApplications(ctx context.Context, arg ListAdminApplicationsParams) ([]PartnerApplication, error) {
	rows, err := q.db.Query(ctx, listAdminApplications,
		arg.StatusFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerApplication
	for rows.Next() {
		var i PartnerApplication
		if err := rows.Scan(
			&i.ID,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.BusinessName,
			&i.CategoryCode,
			&i.Address,
			&i.Description,
			&i.Status,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAuditLog = `-- name: ListAdminAuditLog :many
SELECT al.id, al.admin_user_id, al.action, al.entity_type, al.entity_id, al.details, al.ip_address, al.created_at,
       au.email AS admin_email,
       au.name AS admin_name
FROM admin_audit_log al
JOIN admin_users au ON au.id = al.admin_user_id
WHERE (
    $1::text = ''
    OR al.action = $1::text
)
AND (
    $2::text = ''
    OR al.entity_type = $2::text
)
ORDER BY al.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminAuditLogParams struct {
	ActionFilter     string `json:"action_filter"`
	EntityTypeFilter string `json:"entity_type_filter"`
	PageOffset       int32  `json:"page_offset"`
	PageLimit        int32  `json:"page_limit"`
}

type ListAdminAuditLogRow struct {
	ID          uuid.UUID   `json:"id"`
	AdminUserID uuid.UUID   `json:"admin_user_id"`
	Action      string      `json:"action"`
	EntityType  pgtype.Text `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Details     []byte      `json:"details"`
	IpAddress   *netip.Addr `json:"ip_address"`
	CreatedAt   time.Time   `json:"created_at"`
	AdminEmail  string      `json:"admin_email"`
	AdminName   string      `json:"admin_name"`
}

func (q *Queries) ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]ListAdminAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLog,
		arg.ActionFilter,
		arg.EntityTypeFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminAuditLogRow
	for rows.Next() {
		var i ListAdminAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.AdminEmail,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminBoxes = `-- name: ListAdminBoxes :many
SELECT sb.id,
       sb.location_id,
       l.name AS location_name,
       l.partner_id,
       p.brand_name AS partner_name,
       sb.name,
       COALESCE(sb.description, '') AS description,
       sb.original_price,
       sb.discount_price,
       sb.quantity_available,
       sb.pickup_time_start,
       sb.pickup_time_end,
       COALESCE(sb.image_url, '') AS image_url,
       sb.status,
       sb.created_at,
       sb.updated_at,
       COUNT(o.id)::int AS total_orders
FROM surprise_boxes sb
JOIN locations l ON l.id = sb.location_id
JOIN partners p ON p.id = l.partner_id
LEFT JOIN orders o ON o.box_id = sb.id
WHERE (
    $1::text = ''
    OR sb.status = $1::text
)
AND (
    $2::text = ''
    OR sb.location_id = $2::uuid
)
AND (
    $3::text = ''
    OR sb.name ILIKE '%' || $3::text || '%'
    OR l.name ILIKE '%' || $3::text || '%'
    OR p.brand_name ILIKE '%' || $3::text || '%'
)
GROUP BY sb.id, l.id, p.id
ORDER BY sb.created_at DESC
LIMIT $5 OFFSET $4
`

type ListAdminBoxesParams struct {
	StatusFilter     string `json:"status_filter"`
	LocationIDFilter string `json:"location_id_filter"`
	Search           string `json:"search"`
	PageOffset       int32  `json:"page_offset"`
	PageLimit        int32  `json:"page_limit"`
}

type ListAdminBoxesRow struct {
	ID                uuid.UUID      `json:"id"`
	LocationID        uuid.UUID      `json:"location_id"`
	LocationName      string         `json:"location_name"`
	PartnerID         uuid.UUID      `json:"partner_id"`
	PartnerName       string         `json:"partner_name"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	OriginalPrice     pgtype.Numeric `json:"original_price"`
	DiscountPrice     pgtype.Numeric `json:"discount_price"`
	QuantityAvailable int32          `json:"quantity_available"`
	PickupTimeStart   pgtype.Time    `json:"pickup_time_start"`
	PickupTimeEnd     pgtype.Time    `json:"pickup_time_end"`
	ImageUrl          string         `json:"image_url"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	TotalOrders       int32          `json:"total_orders"`
}

func (q *Queries) ListAdminBoxes(ctx context.Context, arg ListAdminBoxesParams) ([]ListAdminBoxesRow, error) {
	rows, err := q.db.Query(ctx, listAdminBoxes,
		arg.StatusFilter,
		arg.LocationIDFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminBoxesRow
	for rows.Next() {
		var i ListAdminBoxesRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.LocationName,
			&i.PartnerID,
			&i.PartnerName,
			&i.Name,
			&i.Description,
			&i.OriginalPrice,
			&i.DiscountPrice,
			&i.QuantityAvailable,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalOrders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminCustomers = `-- name: ListAdminCustomers :many
SELECT u.id,
       u.phone,
       u.name,
       u.created_at,
       u.updated_at,
       COUNT(o.id)::int AS total_orders,
       COALESCE(SUM(o.amount) FILTER (WHERE o.status IN ('completed', 'picked_up')), 0)::numeric AS total_spent
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE (
    $1::text = ''
    OR u.phone ILIKE '%' || $1::text || '%'
    OR u.name ILIKE '%' || $1::text || '%'
)
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $2
`

type ListAdminCustomersParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListAdminCustomersRow struct {
	ID          uuid.UUID      `json:"id"`
	Phone       string         `json:"phone"`
	Name        pgtype.Text    `json:"name"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	TotalOrders int32          `json:"total_orders"`
	TotalSpent  pgtype.Numeric `json:"total_spent"`
}

func (q *Queries) ListAdminCustomers(ctx context.Context, arg ListAdminCustomersParams) ([]ListAdminCustomersRow, error) {
	rows, err := q.db.Query(ctx, listAdminCustomers, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCustomersRow
	for rows.Next() {
		var i ListAdminCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalOrders,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLocations = `-- name: ListAdminLocations :many
SELECT l.id,
       l.partner_id,
       p.brand_name AS partner_name,
       l.category_code,
       l.name,
       l.address,
       COALESCE(l.phone, '') AS phone,
       COALESCE(l.logo_url, '') AS logo_url,
       COALESCE(l.cover_image_url, '') AS cover_image_url,
       l.status,
       l.created_at,
       l.updated_at,
       COUNT(DISTINCT sb.id)::int AS boxes_count,
       COUNT(DISTINCT o.id)::int AS total_orders
FROM locations l
JOIN partners p ON p.id = l.partner_id
LEFT JOIN surprise_boxes sb ON sb.location_id = l.id
LEFT JOIN orders o ON o.location_id = l.id
WHERE (
    $1::text = ''
    OR l.status = $1::text
)
AND (
    $2::text = ''
    OR l.partner_id = $2::uuid
)
AND (
    $3::text = ''
    OR l.name ILIKE '%' || $3::text || '%'
    OR l.address ILIKE '%' || $3::text || '%'
    OR p.brand_name ILIKE '%' || $3::text || '%'
)
GROUP BY l.id, p.brand_name
ORDER BY l.created_at DESC
LIMIT $5 OFFSET $4
`

type ListAdminLocationsParams struct {
	StatusFilter    string `json:"status_filter"`
	PartnerIDFilter string `json:"partner_id_filter"`
	Search          string `json:"search"`
	PageOffset      int32  `json:"page_offset"`
	PageLimit       int32  `json:"page_limit"`
}

type ListAdminLocationsRow struct {
	ID            uuid.UUID        `json:"id"`
	PartnerID     uuid.UUID        `json:"partner_id"`
	PartnerName   string           `json:"partner_name"`
	CategoryCode  string           `json:"category_code"`
	Name          string           `json:"name"`
	Address       string           `json:"address"`
	Phone         string           `json:"phone"`
	LogoUrl       string           `json:"logo_url"`
	CoverImageUrl string           `json:"cover_image_url"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	BoxesCount    int32            `json:"boxes_count"`
	TotalOrders   int32            `json:"total_orders"`
}

func (q *Queries) ListAdminLocations(ctx context.Context, arg ListAdminLocationsParams) ([]ListAdminLocationsRow, error) {
	rows, err := q.db.Query(ctx, listAdminLocations,
		arg.StatusFilter,
		arg.PartnerIDFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminLocationsRow
	for rows.Next() {
		var i ListAdminLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.PartnerName,
			&i.CategoryCode,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoxesCount,
			&i.TotalOrders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOrders = `-- name: ListAdminOrders :many
SELECT o.id,
       o.user_id,
       u.phone AS customer_phone,
       COALESCE(u.name, '') AS customer_name,
       o.box_id,
       sb.name AS box_name,
       o.location_id,
       l.name AS location_name,
       l.partner_id,
       p.brand_name AS partner_name,
       o.pickup_code,
       o.amount,
       o.pickup_time_start,
       o.pickup_time_end,
       o.status,
       o.created_at,
       o.updated_at
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN surprise_boxes sb ON sb.id = o.box_id
JOIN locations l ON l.id = o.location_id
JOIN partners p ON p.id = l.partner_id
WHERE (
    $1::text = ''
    OR o.status::text = $1::text
)
AND (
    $2::text = ''
    OR o.pickup_code ILIKE '%' || $2::text || '%'
    OR u.phone ILIKE '%' || $2::text || '%'
    OR sb.name ILIKE '%' || $2::text || '%'
    OR l.name ILIKE '%' || $2::text || '%'
    OR p.brand_name ILIKE '%' || $2::text || '%'
)
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminOrdersParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageOffset   int32  `json:"page_offset"`
	PageLimit    int32  `json:"page_limit"`
}

type ListAdminOrdersRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerName    string         `json:"customer_name"`
	BoxID           uuid.UUID      `json:"box_id"`
	BoxName         string         `json:"box_name"`
	LocationID      uuid.UUID      `json:"location_id"`
	LocationName    string         `json:"location_name"`
	PartnerID       uuid.UUID      `json:"partner_id"`
	PartnerName     string         `json:"partner_name"`
	PickupCode      string         `json:"pickup_code"`
	Amount          pgtype.Numeric `json:"amount"`
	PickupTimeStart time.Time      `json:"pickup_time_start"`
	PickupTimeEnd   time.Time      `json:"pickup_time_end"`
	Status          OrderStatus    `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]ListAdminOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminOrders,
		arg.StatusFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOrdersRow
	for rows.Next() {
		var i ListAdminOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerPhone,
			&i.CustomerName,
			&i.BoxID,
			&i.BoxName,
			&i.LocationID,
			&i.LocationName,
			&i.PartnerID,
			&i.PartnerName,
			&i.PickupCode,
			&i.Amount,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPartners = `-- name: ListAdminPartners :many
SELECT p.id,
       p.brand_name,
       COALESCE(pli.legal_name, '') AS legal_name,
       COALESCE(pli.verification_status, '') AS legal_verification_status,
       COALESCE(pli.verification_comment, '') AS legal_verification_comment,
       p.logo_url,
       p.account_type,
       p.commission_rate,
       p.promo_commission_rate,
       p.promo_commission_until,
       p.status,
       p.created_at,
       p.updated_at,
       COUNT(DISTINCT l.id)::int AS locations_count,
       COUNT(DISTINCT o.id)::int AS total_orders,
       COALESCE(SUM(o.amount) FILTER (WHERE o.status IN ('completed', 'picked_up')), 0)::numeric AS total_revenue
FROM partners p
LEFT JOIN partner_legal_info pli ON pli.partner_id = p.id
LEFT JOIN locations l ON l.partner_id = p.id
LEFT JOIN orders o ON o.location_id = l.id
WHERE (
    $1::text = ''
    OR p.status = $1::text
)
AND (
    $2::text = ''
    OR p.brand_name ILIKE '%' || $2::text || '%'
    OR pli.legal_name ILIKE '%' || $2::text || '%'
)
AND (
    $3::text = ''
    OR COALESCE(pli.verification_status, '') = $3::text
)
GROUP BY p.id, pli.legal_name, pli.verification_status, pli.verification_comment
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListAdminPartnersParams struct {
	StatusFilter      string `json:"status_filter"`
	Search            string `json:"search"`
	LegalStatusFilter string `json:"legal_status_filter"`
	PageOffset        int32  `json:"page_offset"`
	PageLimit         int32  `json:"page_limit"`
}

type ListAdminPartnersRow struct {
	ID                       uuid.UUID      `json:"id"`
	BrandName                string         `json:"brand_name"`
	LegalName                string         `json:"legal_name"`
	LegalVerificationStatus  string         `json:"legal_verification_status"`
	LegalVerificationComment string         `json:"legal_verification_comment"`
	LogoUrl                  pgtype.Text    `json:"logo_url"`
	AccountType              pgtype.Text    `json:"account_type"`
	CommissionRate           pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate      pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil     pgtype.Date    `json:"promo_commission_until"`
	Status                   string         `json:"status"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	LocationsCount           int32          `json:"locations_count"`
	TotalOrders              int32          `json:"total_orders"`
	TotalRevenue             pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) ListAdminPartners(ctx context.Context, arg ListAdminPartnersParams) ([]ListAdminPartnersRow, error) {
	rows, err := q.db.Query(ctx, listAdminPartners,
		arg.StatusFilter,
		arg.Search,
		arg.LegalStatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminPartnersRow
	for rows.Next() {
		var i ListAdminPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandName,
			&i.LegalName,
			&i.LegalVerificationStatus,
			&i.LegalVerificationComment,
			&i.LogoUrl,
			&i.AccountType,
			&i.CommissionRate,
			&i.PromoCommissionRate,
			&i.PromoCommissionUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationsCount,
			&i.TotalOrders,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPaymentEvents = `-- name: ListAdminPaymentEvents :many
SELECT id, payment_id, event_type, payload, created_at
FROM payment_events
WHERE payment_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAdminPaymentEventsParams struct {
	PaymentID uuid.UUID `json:"payment_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAdminPaymentEvents(ctx context.Context, arg ListAdminPaymentEventsParams) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listAdminPaymentEvents, arg.PaymentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPayments = `-- name: ListAdminPayments :many
SELECT pay.id,
       pay.order_id,
       pay.provider_payment_id,
       pay.payment_url,
       pay.method,
       pay.provider,
       pay.amount,
       pay.status,
       pay.paid_at,
       pay.created_at,
       pay.updated_at,
       o.pickup_code,
       u.phone AS customer_phone,
       l.name AS location_name,
       p.brand_name AS partner_name
FROM payments pay
JOIN orders o ON o.id = pay.order_id
JOIN users u ON u.id = o.user_id
JOIN locations l ON l.id = o.location_id
JOIN partners p ON p.id = l.partner_id
WHERE (
    $1::text = ''
    OR pay.status::text = $1::text
)
AND (
    $2::text = ''
    OR pay.provider_payment_id ILIKE '%' || $2::text || '%'
    OR o.pickup_code ILIKE '%' || $2::text || '%'
    OR u.phone ILIKE '%' || $2::text || '%'
)
ORDER BY pay.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminPaymentsParams struct {
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageOffset   int32  `json:"page_offset"`
	PageLimit    int32  `json:"page_limit"`
}

type ListAdminPaymentsRow struct {
	ID                uuid.UUID           `json:"id"`
	OrderID           uuid.UUID           `json:"order_id"`
	ProviderPaymentID pgtype.Text         `json:"provider_payment_id"`
	PaymentUrl        pgtype.Text         `json:"payment_url"`
	Method            NullPaymentMethod   `json:"method"`
	Provider          NullPaymentProvider `json:"provider"`
	Amount            pgtype.Numeric      `json:"amount"`
	Status            PaymentStatus       `json:"status"`
	PaidAt            pgtype.Timestamptz  `json:"paid_at"`
	CreatedAt         time.Time           `json:"created_at"`
	UpdatedAt         time.Time           `json:"updated_at"`
	PickupCode        string              `json:"pickup_code"`
	CustomerPhone     string              `json:"customer_phone"`
	LocationName      string              `json:"location_name"`
	PartnerName       string              `json:"partner_name"`
}

func (q *Queries) ListAdminPayments(ctx context.Context, arg ListAdminPaymentsParams) ([]ListAdminPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminPayments,
		arg.StatusFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminPaymentsRow
	for rows.Next() {
		var i ListAdminPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProviderPaymentID,
			&i.PaymentUrl,
			&i.Method,
			&i.Provider,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PickupCode,
			&i.CustomerPhone,
			&i.LocationName,
			&i.PartnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, password_hash, name, role, is_active, last_login_at, created_at, updated_at
FROM admin_users
WHERE (
    $1::text = ''
    OR email ILIKE '%' || $1::text || '%'
    OR name ILIKE '%' || $1::text || '%'
)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAdminUsersParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdminUsers, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUser
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationReviewed = `-- name: MarkApplicationReviewed :execrows
UPDATE partner_applications
SET reviewed_by = $2,
    reviewed_at = NOW()
WHERE id = $1
`

type MarkApplicationReviewedParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) MarkApplicationReviewed(ctx context.Context, arg MarkApplicationReviewedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markApplicationReviewed, arg.ID, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectPartnerLegalInfo = `-- name: RejectPartnerLegalInfo :one
UPDATE partner_legal_info
SET verification_status = 'failed',
    verification_comment = $2,
    verified_by = $3,
    verified_at = NOW(),
    updated_at = NOW()
WHERE partner_id = $1
RETURNING partner_id, inn, ogrn, kpp, legal_address, created_at, updated_at, legal_name, verification_status, verification_comment, verified_by, verified_at
`

type RejectPartnerLegalInfoParams struct {
	PartnerID           uuid.UUID   `json:"partner_id"`
	VerificationComment pgtype.Text `json:"verification_comment"`
	VerifiedBy          pgtype.UUID `json:"verified_by"`
}

func (q *Queries) RejectPartnerLegalInfo(ctx context.Context, arg RejectPartnerLegalInfoParams) (PartnerLegalInfo, error) {
	row := q.db.QueryRow(ctx, rejectPartnerLegalInfo, arg.PartnerID, arg.VerificationComment, arg.VerifiedBy)
	var i PartnerLegalInfo
	err := row.Scan(
		&i.PartnerID,
		&i.Inn,
		&i.Ogrn,
		&i.Kpp,
		&i.LegalAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.VerificationStatus,
		&i.VerificationComment,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}

const updateAdminBoxStatus = `-- name: UpdateAdminBoxStatus :one
UPDATE surprise_boxes
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at
`

type UpdateAdminBoxStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAdminBoxStatus(ctx context.Context, arg UpdateAdminBoxStatusParams) (SurpriseBox, error) {
	row := q.db.QueryRow(ctx, updateAdminBoxStatus, arg.ID, arg.Status)
	var i SurpriseBox
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.OriginalPrice,
		&i.DiscountPrice,
		&i.QuantityAvailable,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admin_users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminLocationStatus = `-- name: UpdateAdminLocationStatus :one
UPDATE locations
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type UpdateAdminLocationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAdminLocationStatus(ctx context.Context, arg UpdateAdminLocationStatusParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateAdminLocationStatus, arg.ID, arg.Status)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminPartner = `-- name: UpdateAdminPartner :one
UPDATE partners
SET status = COALESCE($1, status),
    commission_rate = COALESCE($2, commission_rate),
    promo_commission_rate = $3,
    promo_commission_until = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at
`

type UpdateAdminPartnerParams struct {
	Status               pgtype.Text    `json:"status"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	ID                   uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAdminPartner(ctx context.Context, arg UpdateAdminPartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, updateAdminPartner,
		arg.Status,
		arg.CommissionRate,
		arg.PromoCommissionRate,
		arg.PromoCommissionUntil,
		arg.ID,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminUser = `-- name: UpdateAdminUser :one
UPDATE admin_users
SET name = COALESCE($1, name),
    role = COALESCE($2, role),
    is_active = COALESCE($3, is_active),
    updated_at = NOW()
WHERE id = $4
RETURNING id, email, password_hash, name, role, is_active, last_login_at, created_at, updated_at
`

type UpdateAdminUserParams struct {
	Name     pgtype.Text `json:"name"`
	Role     pgtype.Text `json:"role"`
	IsActive pgtype.Bool `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, updateAdminUser,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyPartnerLegalInfo = `-- name: VerifyPartnerLegalInfo :one
UPDATE partner_legal_info
SET verification_status = 'verified',
    verification_comment = NULL,
    verified_by = $2,
    verified_at = NOW(),
    updated_at = NOW()
WHERE partner_id = $1
RETURNING partner_id, inn, ogrn, kpp, legal_address, created_at, updated_at, legal_name, verification_status, verification_comment, verified_by, verified_at
`

type VerifyPartnerLegalInfoParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	VerifiedBy pgtype.UUID `json:"verified_by"`
}

func (q *Queries) VerifyPartnerLegalInfo(ctx context.Context, arg VerifyPartnerLegalInfoParams) (PartnerLegalInfo, error) {
	row := q.db.QueryRow(ctx, verifyPartnerLegalInfo, arg.PartnerID, arg.VerifiedBy)
	var i PartnerLegalInfo
	err := row.Scan(
		&i.PartnerID,
		&i.Inn,
		&i.Ogrn,
		&i.Kpp,
		&i.LegalAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.VerificationStatus,
		&i.VerificationComment,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}
