// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBox = `-- name: CreateBox :one
INSERT INTO surprise_boxes (
    name, description, original_price, discount_price, quantity_available,
    pickup_time_start, pickup_time_end, image_url, status, location_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at
`

type CreateBoxParams struct {
	Name              string         `json:"name"`
	Description       pgtype.Text    `json:"description"`
	OriginalPrice     pgtype.Numeric `json:"original_price"`
	DiscountPrice     pgtype.Numeric `json:"discount_price"`
	QuantityAvailable int32          `json:"quantity_available"`
	PickupTimeStart   pgtype.Time    `json:"pickup_time_start"`
	PickupTimeEnd     pgtype.Time    `json:"pickup_time_end"`
	ImageUrl          pgtype.Text    `json:"image_url"`
	Status            string         `json:"status"`
	LocationID        uuid.UUID      `json:"location_id"`
}

// Create a new box
func (q *Queries) CreateBox(ctx context.Context, arg CreateBoxParams) (SurpriseBox, error) {
	row := q.db.QueryRow(ctx, createBox,
		arg.Name,
		arg.Description,
		arg.OriginalPrice,
		arg.DiscountPrice,
		arg.QuantityAvailable,
		arg.PickupTimeStart,
		arg.PickupTimeEnd,
		arg.ImageUrl,
		arg.Status,
		arg.LocationID,
	)
	var i SurpriseBox
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.OriginalPrice,
		&i.DiscountPrice,
		&i.QuantityAvailable,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM surprise_boxes WHERE id = $1
`

// Delete a box
func (q *Queries) DeleteBox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBox, id)
	return err
}

const findBoxByID = `-- name: FindBoxByID :one
SELECT id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at FROM surprise_boxes WHERE id = $1
`

// Get a box by ID
func (q *Queries) FindBoxByID(ctx context.Context, id uuid.UUID) (SurpriseBox, error) {
	row := q.db.QueryRow(ctx, findBoxByID, id)
	var i SurpriseBox
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.OriginalPrice,
		&i.DiscountPrice,
		&i.QuantityAvailable,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBoxesByLocationID = `-- name: ListActiveBoxesByLocationID :many
SELECT id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at FROM surprise_boxes 
WHERE location_id = $1 AND status = 'active' AND quantity_available > 0
`

// List active boxes by location ID
func (q *Queries) ListActiveBoxesByLocationID(ctx context.Context, locationID uuid.UUID) ([]SurpriseBox, error) {
	rows, err := q.db.Query(ctx, listActiveBoxesByLocationID, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurpriseBox
	for rows.Next() {
		var i SurpriseBox
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.OriginalPrice,
			&i.DiscountPrice,
			&i.QuantityAvailable,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxesByLocationID = `-- name: ListBoxesByLocationID :many
SELECT id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at FROM surprise_boxes WHERE location_id = $1
`

// List boxes by location ID
func (q *Queries) ListBoxesByLocationID(ctx context.Context, locationID uuid.UUID) ([]SurpriseBox, error) {
	rows, err := q.db.Query(ctx, listBoxesByLocationID, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurpriseBox
	for rows.Next() {
		var i SurpriseBox
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.OriginalPrice,
			&i.DiscountPrice,
			&i.QuantityAvailable,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBox = `-- name: UpdateBox :one
UPDATE surprise_boxes SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    original_price = COALESCE($4, original_price),
    discount_price = COALESCE($5, discount_price),
    quantity_available = COALESCE($6, quantity_available),
    pickup_time_start = COALESCE($7, pickup_time_start),
    pickup_time_end = COALESCE($8, pickup_time_end),
    image_url = COALESCE($9, image_url),
    status = COALESCE($10, status)
WHERE id = $1 RETURNING id, location_id, name, description, original_price, discount_price, quantity_available, pickup_time_start, pickup_time_end, image_url, status, created_at, updated_at
`

type UpdateBoxParams struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	Description       pgtype.Text    `json:"description"`
	OriginalPrice     pgtype.Numeric `json:"original_price"`
	DiscountPrice     pgtype.Numeric `json:"discount_price"`
	QuantityAvailable int32          `json:"quantity_available"`
	PickupTimeStart   pgtype.Time    `json:"pickup_time_start"`
	PickupTimeEnd     pgtype.Time    `json:"pickup_time_end"`
	ImageUrl          pgtype.Text    `json:"image_url"`
	Status            string         `json:"status"`
}

// Update an existing box
func (q *Queries) UpdateBox(ctx context.Context, arg UpdateBoxParams) (SurpriseBox, error) {
	row := q.db.QueryRow(ctx, updateBox,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OriginalPrice,
		arg.DiscountPrice,
		arg.QuantityAvailable,
		arg.PickupTimeStart,
		arg.PickupTimeEnd,
		arg.ImageUrl,
		arg.Status,
	)
	var i SurpriseBox
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.OriginalPrice,
		&i.DiscountPrice,
		&i.QuantityAvailable,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
