// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO users (phone)
VALUES ($1)
RETURNING id
`

// Create new customer
func (q *Queries) CreateCustomer(ctx context.Context, phone string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCustomer, phone)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id, phone, name, created_at, updated_at FROM users WHERE id = $1
`

// Get customer by ID
func (q *Queries) FindCustomerByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findCustomerByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCustomerByPhone = `-- name: FindCustomerByPhone :one
SELECT id, phone, name, created_at, updated_at FROM users WHERE phone = $1
`

// Get customer by phone
func (q *Queries) FindCustomerByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, findCustomerByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one
UPDATE users
SET name = $2
WHERE id = $1
RETURNING id, phone, name, created_at, updated_at
`

type UpdateCustomerProfileParams struct {
	ID   uuid.UUID   `json:"id"`
	Name pgtype.Text `json:"name"`
}

// Update customer profile
func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
