// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eco.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEcoAggregateByUserID = `-- name: GetEcoAggregateByUserID :many
SELECT
    l.category_code                                              AS category_code,
    COUNT(*)                                                     AS picked_count,
    COALESCE(SUM(sb.original_price - sb.discount_price), 0)::numeric AS savings
FROM orders o
    JOIN surprise_boxes sb ON sb.id = o.box_id
    JOIN locations l ON l.id = o.location_id
WHERE o.user_id = $1
  AND o.picked_up_at IS NOT NULL
GROUP BY l.category_code
`

type GetEcoAggregateByUserIDRow struct {
	CategoryCode string         `json:"category_code"`
	PickedCount  int64          `json:"picked_count"`
	Savings      pgtype.Numeric `json:"savings"`
}

// Aggregates picked-up orders for a customer grouped by location category.
// "Picked up" = orders that physically reached the customer (picked_up_at IS NOT NULL).
// Returned per-category counts let the application layer multiply by the
// average-weight coefficient that lives in Go code (see internal/modules/eco/coefficients.go).
func (q *Queries) GetEcoAggregateByUserID(ctx context.Context, userID uuid.UUID) ([]GetEcoAggregateByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getEcoAggregateByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEcoAggregateByUserIDRow
	for rows.Next() {
		var i GetEcoAggregateByUserIDRow
		if err := rows.Scan(&i.CategoryCode, &i.PickedCount, &i.Savings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
