// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBoxesByLocationID = `-- name: CountActiveBoxesByLocationID :one
SELECT COUNT(*) 
FROM surprise_boxes 
WHERE location_id = $1 
    AND status = 'active' 
    AND quantity_available > 0
`

// Count active boxes by location ID
func (q *Queries) CountActiveBoxesByLocationID(ctx context.Context, locationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBoxesByLocationID, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveLocations = `-- name: CountActiveLocations :one
SELECT COUNT(*)
FROM locations
WHERE status = 'active'
    AND ($1::varchar IS NULL OR category_code = $1::varchar)
`

// Count active locations for pagination
func (q *Queries) CountActiveLocations(ctx context.Context, categoryCode pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLocations, categoryCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLocationDetailsByID = `-- name: GetLocationDetailsByID :one
SELECT 
    l.id,
    l.partner_id,
    l.name,
    l.address,
    l.phone,
    l.logo_url,
    l.cover_image_url,
    l.gallery_urls,
    l.working_hours,
    l.status,
    l.category_code,
    lc.name_ru as category_name,
    lc.icon_url as category_icon_url,
    lc.color as category_color,
    ST_X(l.location::geometry) as longitude,
    ST_Y(l.location::geometry) as latitude,
    l.created_at,
    l.updated_at
FROM locations l
JOIN location_categories lc ON l.category_code = lc.code
WHERE l.id = $1
`

type GetLocationDetailsByIDRow struct {
	ID              uuid.UUID        `json:"id"`
	PartnerID       uuid.UUID        `json:"partner_id"`
	Name            string           `json:"name"`
	Address         string           `json:"address"`
	Phone           pgtype.Text      `json:"phone"`
	LogoUrl         pgtype.Text      `json:"logo_url"`
	CoverImageUrl   pgtype.Text      `json:"cover_image_url"`
	GalleryUrls     []string         `json:"gallery_urls"`
	WorkingHours    []byte           `json:"working_hours"`
	Status          string           `json:"status"`
	CategoryCode    string           `json:"category_code"`
	CategoryName    string           `json:"category_name"`
	CategoryIconUrl pgtype.Text      `json:"category_icon_url"`
	CategoryColor   pgtype.Text      `json:"category_color"`
	Longitude       interface{}      `json:"longitude"`
	Latitude        interface{}      `json:"latitude"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

// Get location details by ID with category info
func (q *Queries) GetLocationDetailsByID(ctx context.Context, id uuid.UUID) (GetLocationDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, getLocationDetailsByID, id)
	var i GetLocationDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CategoryCode,
		&i.CategoryName,
		&i.CategoryIconUrl,
		&i.CategoryColor,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchLocations = `-- name: SearchLocations :many

SELECT
    l.id,
    l.partner_id,
    l.name,
    l.address,
    l.phone,
    l.logo_url,
    l.cover_image_url,
    l.gallery_urls,
    l.working_hours,
    l.status,
    l.category_code,
    lc.name_ru as category_name,
    lc.icon_url as category_icon_url,
    lc.color as category_color,
    ST_X(l.location::geometry) as longitude,
    ST_Y(l.location::geometry) as latitude,
    COALESCE((SELECT COUNT(*) FROM surprise_boxes sb WHERE sb.location_id = l.id AND sb.status = 'active' AND sb.quantity_available > 0), 0)::int as active_boxes_count,
    l.created_at,
    l.updated_at
FROM locations l
JOIN location_categories lc ON l.category_code = lc.code
WHERE l.status = 'active'
    AND ($1::varchar IS NULL OR l.category_code = $1::varchar)
ORDER BY l.created_at DESC
LIMIT $3 OFFSET $2
`

type SearchLocationsParams struct {
	CategoryCode pgtype.Text `json:"category_code"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

type SearchLocationsRow struct {
	ID               uuid.UUID        `json:"id"`
	PartnerID        uuid.UUID        `json:"partner_id"`
	Name             string           `json:"name"`
	Address          string           `json:"address"`
	Phone            pgtype.Text      `json:"phone"`
	LogoUrl          pgtype.Text      `json:"logo_url"`
	CoverImageUrl    pgtype.Text      `json:"cover_image_url"`
	GalleryUrls      []string         `json:"gallery_urls"`
	WorkingHours     []byte           `json:"working_hours"`
	Status           string           `json:"status"`
	CategoryCode     string           `json:"category_code"`
	CategoryName     string           `json:"category_name"`
	CategoryIconUrl  pgtype.Text      `json:"category_icon_url"`
	CategoryColor    pgtype.Text      `json:"category_color"`
	Longitude        interface{}      `json:"longitude"`
	Latitude         interface{}      `json:"latitude"`
	ActiveBoxesCount int32            `json:"active_boxes_count"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

// Location queries for customer app
// Search locations
func (q *Queries) SearchLocations(ctx context.Context, arg SearchLocationsParams) ([]SearchLocationsRow, error) {
	rows, err := q.db.Query(ctx, searchLocations, arg.CategoryCode, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLocationsRow
	for rows.Next() {
		var i SearchLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.WorkingHours,
			&i.Status,
			&i.CategoryCode,
			&i.CategoryName,
			&i.CategoryIconUrl,
			&i.CategoryColor,
			&i.Longitude,
			&i.Latitude,
			&i.ActiveBoxesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
