// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (
    filename, original_filename, storage_key, url, content_type, size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, filename, original_filename, storage_key, url, content_type, size_bytes, uploaded_at
`

type CreateMediaFileParams struct {
	Filename         string `json:"filename"`
	OriginalFilename string `json:"original_filename"`
	StorageKey       string `json:"storage_key"`
	Url              string `json:"url"`
	ContentType      string `json:"content_type"`
	SizeBytes        int64  `json:"size_bytes"`
}

// Create a new media file record
func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.Filename,
		arg.OriginalFilename,
		arg.StorageKey,
		arg.Url,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.Url,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE id = $1
`

// Delete media file record
func (q *Queries) DeleteMediaFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, id)
	return err
}

const findMediaFileByID = `-- name: FindMediaFileByID :one
SELECT id, filename, original_filename, storage_key, url, content_type, size_bytes, uploaded_at FROM media_files WHERE id = $1
`

// Get media file by ID
func (q *Queries) FindMediaFileByID(ctx context.Context, id uuid.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, findMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.Url,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const listMediaFiles = `-- name: ListMediaFiles :many
SELECT id, filename, original_filename, storage_key, url, content_type, size_bytes, uploaded_at FROM media_files
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// List all media files (paginated)
func (q *Queries) ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.StorageKey,
			&i.Url,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
