// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusCompleted OrderStatus = "completed"
	OrderStatusPickedUp  OrderStatus = "picked_up"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRefunded  OrderStatus = "refunded"
	OrderStatusDisputed  OrderStatus = "disputed"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

// Заведения (точки партнёров)
type Location struct {
	ID            uuid.UUID        `json:"id"`
	PartnerID     uuid.UUID        `json:"partner_id"`
	CategoryCode  string           `json:"category_code"`
	Name          string           `json:"name"`
	Address       string           `json:"address"`
	Location      interface{}      `json:"location"`
	Phone         pgtype.Text      `json:"phone"`
	LogoUrl       pgtype.Text      `json:"logo_url"`
	CoverImageUrl pgtype.Text      `json:"cover_image_url"`
	GalleryUrls   []string         `json:"gallery_urls"`
	WorkingHours  []byte           `json:"working_hours"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type LocationCategory struct {
	Code      string      `json:"code"`
	NameRu    string      `json:"name_ru"`
	NameEn    pgtype.Text `json:"name_en"`
	IconUrl   pgtype.Text `json:"icon_url"`
	Color     pgtype.Text `json:"color"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

type MediaFile struct {
	ID               uuid.UUID        `json:"id"`
	Filename         string           `json:"filename"`
	OriginalFilename string           `json:"original_filename"`
	StorageKey       string           `json:"storage_key"`
	Url              string           `json:"url"`
	ContentType      string           `json:"content_type"`
	SizeBytes        int64            `json:"size_bytes"`
	UploadedAt       pgtype.Timestamp `json:"uploaded_at"`
}

// Заказы
type Order struct {
	ID                          uuid.UUID          `json:"id"`
	UserID                      uuid.UUID          `json:"user_id"`
	BoxID                       uuid.UUID          `json:"box_id"`
	LocationID                  uuid.UUID          `json:"location_id"`
	PickupCode                  string             `json:"pickup_code"`
	QrCodeUrl                   pgtype.Text        `json:"qr_code_url"`
	Amount                      pgtype.Numeric     `json:"amount"`
	PickupTimeStart             time.Time          `json:"pickup_time_start"`
	PickupTimeEnd               time.Time          `json:"pickup_time_end"`
	Status                      OrderStatus        `json:"status"`
	PartnerConfirmationDeadline time.Time          `json:"partner_confirmation_deadline"`
	PartnerConfirmedAt          pgtype.Timestamptz `json:"partner_confirmed_at"`
	PartnerConfirmedBy          pgtype.UUID        `json:"partner_confirmed_by"`
	CancellationReason          pgtype.Text        `json:"cancellation_reason"`
	CancelledAt                 pgtype.Timestamptz `json:"cancelled_at"`
	PickedUpAt                  pgtype.Timestamptz `json:"picked_up_at"`
	PickedUpConfirmedBy         pgtype.UUID        `json:"picked_up_confirmed_by"`
	UserConfirmedAt             pgtype.Timestamptz `json:"user_confirmed_at"`
	AutoCompletedAt             pgtype.Timestamptz `json:"auto_completed_at"`
	CreatedAt                   time.Time          `json:"created_at"`
	UpdatedAt                   time.Time          `json:"updated_at"`
}

// Партнёры (юридические лица)
type Partner struct {
	ID                   uuid.UUID      `json:"id"`
	BrandName            string         `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type PartnerApplication struct {
	ID              uuid.UUID          `json:"id"`
	ContactName     string             `json:"contact_name"`
	ContactEmail    string             `json:"contact_email"`
	ContactPhone    string             `json:"contact_phone"`
	BusinessName    string             `json:"business_name"`
	CategoryCode    pgtype.Text        `json:"category_code"`
	Address         pgtype.Text        `json:"address"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	CreatedAt       time.Time          `json:"created_at"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
}

// Сотрудники партнёров
type PartnerEmployee struct {
	ID                 uuid.UUID          `json:"id"`
	PartnerID          uuid.UUID          `json:"partner_id"`
	LocationID         pgtype.UUID        `json:"location_id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	Name               pgtype.Text        `json:"name"`
	MustChangePassword pgtype.Bool        `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

// Юридическая информация партнёров
type PartnerLegalInfo struct {
	PartnerID    uuid.UUID        `json:"partner_id"`
	Inn          string           `json:"inn"`
	Ogrn         pgtype.Text      `json:"ogrn"`
	Kpp          pgtype.Text      `json:"kpp"`
	LegalAddress string           `json:"legal_address"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LegalName    string           `json:"legal_name"`
}

// Сюрприз-боксы для продажи
type SurpriseBox struct {
	ID                uuid.UUID      `json:"id"`
	LocationID        uuid.UUID      `json:"location_id"`
	Name              string         `json:"name"`
	Description       pgtype.Text    `json:"description"`
	OriginalPrice     pgtype.Numeric `json:"original_price"`
	DiscountPrice     pgtype.Numeric `json:"discount_price"`
	QuantityAvailable int32          `json:"quantity_available"`
	PickupTimeStart   pgtype.Time    `json:"pickup_time_start"`
	PickupTimeEnd     pgtype.Time    `json:"pickup_time_end"`
	ImageUrl          pgtype.Text    `json:"image_url"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

// Пользователи приложения
type User struct {
	ID        uuid.UUID   `json:"id"`
	Phone     string      `json:"phone"`
	Name      pgtype.Text `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
