// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Партнёры (юридические лица)
type Partner struct {
	ID                   uuid.UUID      `json:"id"`
	LegalName            string         `json:"legal_name"`
	BrandName            pgtype.Text    `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type PartnerApplication struct {
	ID              uuid.UUID          `json:"id"`
	ContactName     string             `json:"contact_name"`
	ContactEmail    string             `json:"contact_email"`
	ContactPhone    string             `json:"contact_phone"`
	BusinessName    string             `json:"business_name"`
	CategoryCode    pgtype.Text        `json:"category_code"`
	Address         pgtype.Text        `json:"address"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	CreatedAt       time.Time          `json:"created_at"`
}
