// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOrdersByLocationID = `-- name: CountActiveOrdersByLocationID :one
SELECT COUNT(*)
FROM orders o
WHERE o.location_id = $1
  AND o.status IN ('paid', 'confirmed')
`

func (q *Queries) CountActiveOrdersByLocationID(ctx context.Context, locationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersByLocationID, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByCustomerID = `-- name: CountOrdersByCustomerID :one
SELECT COUNT(*)
FROM orders o
WHERE o.user_id = $1
  AND (
    $2 = ''
    OR o.status::text = $2
  )
`

type CountOrdersByCustomerIDParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountOrdersByCustomerID(ctx context.Context, arg CountOrdersByCustomerIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByCustomerID, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByPartnerID = `-- name: CountOrdersByPartnerID :one
SELECT COUNT(*)
FROM orders o
  JOIN locations l ON o.location_id = l.id
WHERE l.partner_id = $1
  AND (
    $2 = ''
    OR o.status::text = $2
  )
`

type CountOrdersByPartnerIDParams struct {
	PartnerID uuid.UUID   `json:"partner_id"`
	Column2   interface{} `json:"column_2"`
}

func (q *Queries) CountOrdersByPartnerID(ctx context.Context, arg CountOrdersByPartnerIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByPartnerID, arg.PartnerID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    box_id,
    location_id,
    pickup_code,
    qr_code_url,
    amount,
    pickup_time_start,
    pickup_time_end,
    status,
    partner_confirmation_deadline
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, box_id, location_id, pickup_code, qr_code_url, amount, pickup_time_start, pickup_time_end, status, partner_confirmation_deadline, partner_confirmed_at, partner_confirmed_by, cancellation_reason, cancelled_at, picked_up_at, picked_up_confirmed_by, user_confirmed_at, auto_completed_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID                      uuid.UUID      `json:"user_id"`
	BoxID                       uuid.UUID      `json:"box_id"`
	LocationID                  uuid.UUID      `json:"location_id"`
	PickupCode                  string         `json:"pickup_code"`
	QrCodeUrl                   pgtype.Text    `json:"qr_code_url"`
	Amount                      pgtype.Numeric `json:"amount"`
	PickupTimeStart             time.Time      `json:"pickup_time_start"`
	PickupTimeEnd               time.Time      `json:"pickup_time_end"`
	Status                      OrderStatus    `json:"status"`
	PartnerConfirmationDeadline time.Time      `json:"partner_confirmation_deadline"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.BoxID,
		arg.LocationID,
		arg.PickupCode,
		arg.QrCodeUrl,
		arg.Amount,
		arg.PickupTimeStart,
		arg.PickupTimeEnd,
		arg.Status,
		arg.PartnerConfirmationDeadline,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoxID,
		&i.LocationID,
		&i.PickupCode,
		&i.QrCodeUrl,
		&i.Amount,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.Status,
		&i.PartnerConfirmationDeadline,
		&i.PartnerConfirmedAt,
		&i.PartnerConfirmedBy,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.PickedUpAt,
		&i.PickedUpConfirmedBy,
		&i.UserConfirmedAt,
		&i.AutoCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveOrdersByLocationId = `-- name: FindActiveOrdersByLocationId :many
SELECT o.id, o.user_id, o.box_id, o.location_id, o.pickup_code, o.qr_code_url, o.amount, o.pickup_time_start, o.pickup_time_end, o.status, o.partner_confirmation_deadline, o.partner_confirmed_at, o.partner_confirmed_by, o.cancellation_reason, o.cancelled_at, o.picked_up_at, o.picked_up_confirmed_by, o.user_confirmed_at, o.auto_completed_at, o.created_at, o.updated_at
FROM orders o
  JOIN surprise_boxes sb ON o.box_id = sb.id
WHERE o.location_id = $1
  AND o.status IN ('pending', 'paid', 'confirmed')
  AND sb.quantity_available > 0
`

func (q *Queries) FindActiveOrdersByLocationId(ctx context.Context, locationID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, findActiveOrdersByLocationId, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BoxID,
			&i.LocationID,
			&i.PickupCode,
			&i.QrCodeUrl,
			&i.Amount,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.Status,
			&i.PartnerConfirmationDeadline,
			&i.PartnerConfirmedAt,
			&i.PartnerConfirmedBy,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.PickedUpAt,
			&i.PickedUpConfirmedBy,
			&i.UserConfirmedAt,
			&i.AutoCompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationOrderByID = `-- name: GetLocationOrderByID :one
SELECT o.id,
  o.status
FROM orders o
WHERE o.id = $1
  AND o.location_id = $2
`

type GetLocationOrderByIDParams struct {
	ID         uuid.UUID `json:"id"`
	LocationID uuid.UUID `json:"location_id"`
}

type GetLocationOrderByIDRow struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) GetLocationOrderByID(ctx context.Context, arg GetLocationOrderByIDParams) (GetLocationOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getLocationOrderByID, arg.ID, arg.LocationID)
	var i GetLocationOrderByIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLocationOrderByPickupCode = `-- name: GetLocationOrderByPickupCode :one
SELECT o.id,
  o.pickup_code,
  o.status,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  u.phone AS customer_phone,
  COALESCE(u.name, '') AS customer_name,
  o.pickup_time_start,
  o.pickup_time_end,
  o.created_at
FROM orders o
  JOIN surprise_boxes sb ON sb.id = o.box_id
  JOIN users u ON u.id = o.user_id
WHERE o.pickup_code = $1
  AND o.location_id = $2
  AND o.status IN ('paid', 'confirmed')
ORDER BY o.created_at DESC
LIMIT 1
`

type GetLocationOrderByPickupCodeParams struct {
	PickupCode string    `json:"pickup_code"`
	LocationID uuid.UUID `json:"location_id"`
}

type GetLocationOrderByPickupCodeRow struct {
	ID              uuid.UUID   `json:"id"`
	PickupCode      string      `json:"pickup_code"`
	Status          OrderStatus `json:"status"`
	BoxName         string      `json:"box_name"`
	BoxImageUrl     string      `json:"box_image_url"`
	CustomerPhone   string      `json:"customer_phone"`
	CustomerName    string      `json:"customer_name"`
	PickupTimeStart time.Time   `json:"pickup_time_start"`
	PickupTimeEnd   time.Time   `json:"pickup_time_end"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) GetLocationOrderByPickupCode(ctx context.Context, arg GetLocationOrderByPickupCodeParams) (GetLocationOrderByPickupCodeRow, error) {
	row := q.db.QueryRow(ctx, getLocationOrderByPickupCode, arg.PickupCode, arg.LocationID)
	var i GetLocationOrderByPickupCodeRow
	err := row.Scan(
		&i.ID,
		&i.PickupCode,
		&i.Status,
		&i.BoxName,
		&i.BoxImageUrl,
		&i.CustomerPhone,
		&i.CustomerName,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, box_id, location_id, pickup_code, qr_code_url, amount, pickup_time_start, pickup_time_end, status, partner_confirmation_deadline, partner_confirmed_at, partner_confirmed_by, cancellation_reason, cancelled_at, picked_up_at, picked_up_confirmed_by, user_confirmed_at, auto_completed_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoxID,
		&i.LocationID,
		&i.PickupCode,
		&i.QrCodeUrl,
		&i.Amount,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.Status,
		&i.PartnerConfirmationDeadline,
		&i.PartnerConfirmedAt,
		&i.PartnerConfirmedBy,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.PickedUpAt,
		&i.PickedUpConfirmedBy,
		&i.UserConfirmedAt,
		&i.AutoCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderChatProjection = `-- name: GetOrderChatProjection :one
SELECT o.id AS order_id,
  o.user_id AS customer_id,
  l.partner_id,
  o.location_id,
  o.status,
  o.updated_at
FROM orders o
  JOIN locations l ON l.id = o.location_id
WHERE o.id = $1
`

type GetOrderChatProjectionRow struct {
	OrderID    uuid.UUID   `json:"order_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	PartnerID  uuid.UUID   `json:"partner_id"`
	LocationID uuid.UUID   `json:"location_id"`
	Status     OrderStatus `json:"status"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

func (q *Queries) GetOrderChatProjection(ctx context.Context, id uuid.UUID) (GetOrderChatProjectionRow, error) {
	row := q.db.QueryRow(ctx, getOrderChatProjection, id)
	var i GetOrderChatProjectionRow
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.PartnerID,
		&i.LocationID,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderDetailsByID = `-- name: GetOrderDetailsByID :one
SELECT o.id,
  o.user_id,
  o.status,
  o.pickup_code,
  COALESCE(o.qr_code_url, '') AS qr_code_url,
  o.amount,
  o.pickup_time_start,
  o.pickup_time_end,
  o.created_at,
  o.partner_confirmed_at,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  l.name AS location_name,
  l.address AS location_address,
  COALESCE(l.phone, '') AS location_phone,
  ST_Y(l.location::geometry) AS location_lat,
  ST_X(l.location::geometry) AS location_lng
FROM orders o
  JOIN surprise_boxes sb ON sb.id = o.box_id
  JOIN locations l ON l.id = o.location_id
WHERE o.id = $1
`

type GetOrderDetailsByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Status             OrderStatus        `json:"status"`
	PickupCode         string             `json:"pickup_code"`
	QrCodeUrl          string             `json:"qr_code_url"`
	Amount             pgtype.Numeric     `json:"amount"`
	PickupTimeStart    time.Time          `json:"pickup_time_start"`
	PickupTimeEnd      time.Time          `json:"pickup_time_end"`
	CreatedAt          time.Time          `json:"created_at"`
	PartnerConfirmedAt pgtype.Timestamptz `json:"partner_confirmed_at"`
	BoxName            string             `json:"box_name"`
	BoxImageUrl        string             `json:"box_image_url"`
	LocationName       string             `json:"location_name"`
	LocationAddress    string             `json:"location_address"`
	LocationPhone      string             `json:"location_phone"`
	LocationLat        interface{}        `json:"location_lat"`
	LocationLng        interface{}        `json:"location_lng"`
}

func (q *Queries) GetOrderDetailsByID(ctx context.Context, id uuid.UUID) (GetOrderDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetailsByID, id)
	var i GetOrderDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.PickupCode,
		&i.QrCodeUrl,
		&i.Amount,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.CreatedAt,
		&i.PartnerConfirmedAt,
		&i.BoxName,
		&i.BoxImageUrl,
		&i.LocationName,
		&i.LocationAddress,
		&i.LocationPhone,
		&i.LocationLat,
		&i.LocationLng,
	)
	return i, err
}

const getPartnerOrderByID = `-- name: GetPartnerOrderByID :one
SELECT o.id,
  o.status
FROM orders o
  JOIN locations l ON l.id = o.location_id
WHERE o.id = $1
  AND l.partner_id = $2
`

type GetPartnerOrderByIDParams struct {
	ID        uuid.UUID `json:"id"`
	PartnerID uuid.UUID `json:"partner_id"`
}

type GetPartnerOrderByIDRow struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) GetPartnerOrderByID(ctx context.Context, arg GetPartnerOrderByIDParams) (GetPartnerOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOrderByID, arg.ID, arg.PartnerID)
	var i GetPartnerOrderByIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getPartnerOrderByPickupCode = `-- name: GetPartnerOrderByPickupCode :one
SELECT o.id,
  o.pickup_code,
  o.status,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  u.phone AS customer_phone,
  COALESCE(u.name, '') AS customer_name,
  o.pickup_time_start,
  o.pickup_time_end,
  o.created_at
FROM orders o
  JOIN surprise_boxes sb ON sb.id = o.box_id
  JOIN users u ON u.id = o.user_id
  JOIN locations l ON l.id = o.location_id
WHERE o.pickup_code = $1
  AND l.partner_id = $2
ORDER BY o.created_at DESC
LIMIT 1
`

type GetPartnerOrderByPickupCodeParams struct {
	PickupCode string    `json:"pickup_code"`
	PartnerID  uuid.UUID `json:"partner_id"`
}

type GetPartnerOrderByPickupCodeRow struct {
	ID              uuid.UUID   `json:"id"`
	PickupCode      string      `json:"pickup_code"`
	Status          OrderStatus `json:"status"`
	BoxName         string      `json:"box_name"`
	BoxImageUrl     string      `json:"box_image_url"`
	CustomerPhone   string      `json:"customer_phone"`
	CustomerName    string      `json:"customer_name"`
	PickupTimeStart time.Time   `json:"pickup_time_start"`
	PickupTimeEnd   time.Time   `json:"pickup_time_end"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) GetPartnerOrderByPickupCode(ctx context.Context, arg GetPartnerOrderByPickupCodeParams) (GetPartnerOrderByPickupCodeRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOrderByPickupCode, arg.PickupCode, arg.PartnerID)
	var i GetPartnerOrderByPickupCodeRow
	err := row.Scan(
		&i.ID,
		&i.PickupCode,
		&i.Status,
		&i.BoxName,
		&i.BoxImageUrl,
		&i.CustomerPhone,
		&i.CustomerName,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOrdersByLocationID = `-- name: ListActiveOrdersByLocationID :many
SELECT o.id,
  o.status,
  o.pickup_code,
  o.created_at,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  COALESCE(u.phone, '') AS customer_phone,
  COALESCE(u.name, '') AS customer_name,
  l.id AS location_id,
  l.name AS location_name,
  l.address AS location_address,
  o.pickup_time_start,
  o.pickup_time_end
FROM orders o
  JOIN surprise_boxes sb ON o.box_id = sb.id
  JOIN users u ON o.user_id = u.id
  JOIN locations l ON o.location_id = l.id
WHERE l.id = $1
  AND o.status IN ('paid', 'confirmed')
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveOrdersByLocationIDParams struct {
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListActiveOrdersByLocationIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Status          OrderStatus `json:"status"`
	PickupCode      string      `json:"pickup_code"`
	CreatedAt       time.Time   `json:"created_at"`
	BoxName         string      `json:"box_name"`
	BoxImageUrl     string      `json:"box_image_url"`
	CustomerPhone   string      `json:"customer_phone"`
	CustomerName    string      `json:"customer_name"`
	LocationID      uuid.UUID   `json:"location_id"`
	LocationName    string      `json:"location_name"`
	LocationAddress string      `json:"location_address"`
	PickupTimeStart time.Time   `json:"pickup_time_start"`
	PickupTimeEnd   time.Time   `json:"pickup_time_end"`
}

func (q *Queries) ListActiveOrdersByLocationID(ctx context.Context, arg ListActiveOrdersByLocationIDParams) ([]ListActiveOrdersByLocationIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersByLocationID, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOrdersByLocationIDRow
	for rows.Next() {
		var i ListActiveOrdersByLocationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PickupCode,
			&i.CreatedAt,
			&i.BoxName,
			&i.BoxImageUrl,
			&i.CustomerPhone,
			&i.CustomerName,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomerID = `-- name: ListOrdersByCustomerID :many
SELECT id, user_id, box_id, location_id, pickup_code, qr_code_url, amount, pickup_time_start, pickup_time_end, status, partner_confirmation_deadline, partner_confirmed_at, partner_confirmed_by, cancellation_reason, cancelled_at, picked_up_at, picked_up_confirmed_by, user_confirmed_at, auto_completed_at, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomerID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomerID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BoxID,
			&i.LocationID,
			&i.PickupCode,
			&i.QrCodeUrl,
			&i.Amount,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
			&i.Status,
			&i.PartnerConfirmationDeadline,
			&i.PartnerConfirmedAt,
			&i.PartnerConfirmedBy,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.PickedUpAt,
			&i.PickedUpConfirmedBy,
			&i.UserConfirmedAt,
			&i.AutoCompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomerIDFiltered = `-- name: ListOrdersByCustomerIDFiltered :many
SELECT o.id,
  o.status,
  o.pickup_code,
  o.amount,
  o.pickup_time_start,
  o.created_at,
  sb.name AS box_name,
  l.name AS location_name,
  EXISTS(
    SELECT 1
    FROM reviews r
    WHERE r.order_id = o.id
  ) AS has_review
FROM orders o
  JOIN surprise_boxes sb ON o.box_id = sb.id
  JOIN locations l ON o.location_id = l.id
WHERE o.user_id = $1
  AND (
    $2 = ''
    OR o.status::text = $2
  )
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrdersByCustomerIDFilteredParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListOrdersByCustomerIDFilteredRow struct {
	ID              uuid.UUID      `json:"id"`
	Status          OrderStatus    `json:"status"`
	PickupCode      string         `json:"pickup_code"`
	Amount          pgtype.Numeric `json:"amount"`
	PickupTimeStart time.Time      `json:"pickup_time_start"`
	CreatedAt       time.Time      `json:"created_at"`
	BoxName         string         `json:"box_name"`
	LocationName    string         `json:"location_name"`
	HasReview       bool           `json:"has_review"`
}

func (q *Queries) ListOrdersByCustomerIDFiltered(ctx context.Context, arg ListOrdersByCustomerIDFilteredParams) ([]ListOrdersByCustomerIDFilteredRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomerIDFiltered,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByCustomerIDFilteredRow
	for rows.Next() {
		var i ListOrdersByCustomerIDFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PickupCode,
			&i.Amount,
			&i.PickupTimeStart,
			&i.CreatedAt,
			&i.BoxName,
			&i.LocationName,
			&i.HasReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByPartnerIDFiltered = `-- name: ListOrdersByPartnerIDFiltered :many
SELECT o.id,
  o.status,
  o.pickup_code,
  o.created_at,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  COALESCE(u.phone, '') AS customer_phone,
  COALESCE(u.name, '') AS customer_name,
  l.id AS location_id,
  l.name AS location_name,
  l.address AS location_address,
  o.pickup_time_start,
  o.pickup_time_end
FROM orders o
  JOIN surprise_boxes sb ON o.box_id = sb.id
  JOIN users u ON o.user_id = u.id
  JOIN locations l ON o.location_id = l.id
WHERE l.partner_id = $1
  AND (
    $2 = ''
    OR o.status::text = $2
  )
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrdersByPartnerIDFilteredParams struct {
	PartnerID uuid.UUID   `json:"partner_id"`
	Column2   interface{} `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListOrdersByPartnerIDFilteredRow struct {
	ID              uuid.UUID   `json:"id"`
	Status          OrderStatus `json:"status"`
	PickupCode      string      `json:"pickup_code"`
	CreatedAt       time.Time   `json:"created_at"`
	BoxName         string      `json:"box_name"`
	BoxImageUrl     string      `json:"box_image_url"`
	CustomerPhone   string      `json:"customer_phone"`
	CustomerName    string      `json:"customer_name"`
	LocationID      uuid.UUID   `json:"location_id"`
	LocationName    string      `json:"location_name"`
	LocationAddress string      `json:"location_address"`
	PickupTimeStart time.Time   `json:"pickup_time_start"`
	PickupTimeEnd   time.Time   `json:"pickup_time_end"`
}

func (q *Queries) ListOrdersByPartnerIDFiltered(ctx context.Context, arg ListOrdersByPartnerIDFilteredParams) ([]ListOrdersByPartnerIDFilteredRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByPartnerIDFiltered,
		arg.PartnerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByPartnerIDFilteredRow
	for rows.Next() {
		var i ListOrdersByPartnerIDFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PickupCode,
			&i.CreatedAt,
			&i.BoxName,
			&i.BoxImageUrl,
			&i.CustomerPhone,
			&i.CustomerName,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPickedUp = `-- name: MarkOrderPickedUp :execrows
UPDATE orders
SET status = 'completed',
  picked_up_at = NOW(),
  picked_up_confirmed_by = $2,
  updated_at = NOW()
WHERE id = $1
  AND status = 'confirmed'
`

type MarkOrderPickedUpParams struct {
	ID                  uuid.UUID   `json:"id"`
	PickedUpConfirmedBy pgtype.UUID `json:"picked_up_confirmed_by"`
}

func (q *Queries) MarkOrderPickedUp(ctx context.Context, arg MarkOrderPickedUpParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderPickedUp, arg.ID, arg.PickedUpConfirmedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveBox = `-- name: ReserveBox :execrows
UPDATE surprise_boxes
SET quantity_available = quantity_available - 1
WHERE id = $1
  AND quantity_available > 0
  AND status = 'active'
`

func (q *Queries) ReserveBox(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reserveBox, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, box_id, location_id, pickup_code, qr_code_url, amount, pickup_time_start, pickup_time_end, status, partner_confirmation_deadline, partner_confirmed_at, partner_confirmed_by, cancellation_reason, cancelled_at, picked_up_at, picked_up_confirmed_by, user_confirmed_at, auto_completed_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoxID,
		&i.LocationID,
		&i.PickupCode,
		&i.QrCodeUrl,
		&i.Amount,
		&i.PickupTimeStart,
		&i.PickupTimeEnd,
		&i.Status,
		&i.PartnerConfirmationDeadline,
		&i.PartnerConfirmedAt,
		&i.PartnerConfirmedBy,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.PickedUpAt,
		&i.PickedUpConfirmedBy,
		&i.UserConfirmedAt,
		&i.AutoCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
