// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateLocation = `-- name: ActivateLocation :exec
UPDATE locations SET status = 'active', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ActivateLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateLocation, id)
	return err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM partner_employees WHERE email = $1
    UNION
    SELECT 1 FROM partner_applications WHERE contact_email = $1 AND status = 'pending'
) AS email_exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const closeLocation = `-- name: CloseLocation :exec
UPDATE locations SET status = 'closed', updated_at = NOW() WHERE id = $1
`

func (q *Queries) CloseLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeLocation, id)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO partner_applications (
    contact_name, contact_email, contact_phone, business_name, category_code,
    address, description, status, latitude, longitude
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude
`

type CreateApplicationParams struct {
	ContactName  string        `json:"contact_name"`
	ContactEmail string        `json:"contact_email"`
	ContactPhone string        `json:"contact_phone"`
	BusinessName string        `json:"business_name"`
	CategoryCode pgtype.Text   `json:"category_code"`
	Address      pgtype.Text   `json:"address"`
	Description  pgtype.Text   `json:"description"`
	Status       string        `json:"status"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (PartnerApplication, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.BusinessName,
		arg.CategoryCode,
		arg.Address,
		arg.Description,
		arg.Status,
		arg.Latitude,
		arg.Longitude,
	)
	var i PartnerApplication
	err := row.Scan(
		&i.ID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.BusinessName,
		&i.CategoryCode,
		&i.Address,
		&i.Description,
		&i.Status,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, address, partner_id, category_code, status, location)
VALUES ($1, $2, $3, $4, $5, ST_SetSRID(ST_MakePoint($6, $7), 4326))
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type CreateLocationParams struct {
	Name          string      `json:"name"`
	Address       string      `json:"address"`
	PartnerID     uuid.UUID   `json:"partner_id"`
	CategoryCode  string      `json:"category_code"`
	Status        string      `json:"status"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.Address,
		arg.PartnerID,
		arg.CategoryCode,
		arg.Status,
		arg.StMakepoint,
		arg.StMakepoint_2,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (
    brand_name, logo_url, parent_partner_id, account_type,
    commission_rate, promo_commission_rate, promo_commission_until, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at
`

type CreatePartnerParams struct {
	BrandName            string         `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.BrandName,
		arg.LogoUrl,
		arg.ParentPartnerID,
		arg.AccountType,
		arg.CommissionRate,
		arg.PromoCommissionRate,
		arg.PromoCommissionUntil,
		arg.Status,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerEmployee = `-- name: CreatePartnerEmployee :one
INSERT INTO partner_employees (
    partner_id, location_id, email, password_hash, role, name
) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at
`

type CreatePartnerEmployeeParams struct {
	PartnerID    uuid.UUID   `json:"partner_id"`
	LocationID   pgtype.UUID `json:"location_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Name         pgtype.Text `json:"name"`
}

func (q *Queries) CreatePartnerEmployee(ctx context.Context, arg CreatePartnerEmployeeParams) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, createPartnerEmployee,
		arg.PartnerID,
		arg.LocationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
	)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateLocation = `-- name: DeactivateLocation :exec
UPDATE locations SET status = 'inactive', updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateLocation, id)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM partner_applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deletePartnerEmployee = `-- name: DeletePartnerEmployee :exec
DELETE FROM partner_employees WHERE id = $1
`

func (q *Queries) DeletePartnerEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePartnerEmployee, id)
	return err
}

const findApplicationByID = `-- name: FindApplicationByID :one
SELECT id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude FROM partner_applications WHERE id = $1
`

func (q *Queries) FindApplicationByID(ctx context.Context, id uuid.UUID) (PartnerApplication, error) {
	row := q.db.QueryRow(ctx, findApplicationByID, id)
	var i PartnerApplication
	err := row.Scan(
		&i.ID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.BusinessName,
		&i.CategoryCode,
		&i.Address,
		&i.Description,
		&i.Status,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const findCategoryByCode = `-- name: FindCategoryByCode :one
SELECT code, name_ru, name_en, icon_url, color, sort_order FROM location_categories WHERE code = $1
`

func (q *Queries) FindCategoryByCode(ctx context.Context, code string) (LocationCategory, error) {
	row := q.db.QueryRow(ctx, findCategoryByCode, code)
	var i LocationCategory
	err := row.Scan(
		&i.Code,
		&i.NameRu,
		&i.NameEn,
		&i.IconUrl,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}

const findLocationByID = `-- name: FindLocationByID :one
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) FindLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, findLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLocationsByPartnerID = `-- name: FindLocationsByPartnerID :many
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations WHERE partner_id = $1
`

func (q *Queries) FindLocationsByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, findLocationsByPartnerID, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.CategoryCode,
			&i.Name,
			&i.Address,
			&i.Location,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.WorkingHours,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartnerByID = `-- name: FindPartnerByID :one
SELECT id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at FROM partners WHERE id = $1
`

func (q *Queries) FindPartnerByID(ctx context.Context, id uuid.UUID) (Partner, error) {
	row := q.db.QueryRow(ctx, findPartnerByID, id)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPartnerEmployeeByEmail = `-- name: FindPartnerEmployeeByEmail :one
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE email = $1
`

func (q *Queries) FindPartnerEmployeeByEmail(ctx context.Context, email string) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, findPartnerEmployeeByEmail, email)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPartnerEmployeeByID = `-- name: FindPartnerEmployeeByID :one
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE id = $1
`

func (q *Queries) FindPartnerEmployeeByID(ctx context.Context, id uuid.UUID) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, findPartnerEmployeeByID, id)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerProfile = `-- name: GetPartnerProfile :one
SELECT
    e.id as employee_id, e.name as employee_name, e.email, e.role, e.created_at as employee_created_at, e.must_change_password,
    p.id as partner_id, p.brand_name, p.status as partner_status,
    CASE
        WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
        ELSE p.commission_rate
    END AS commission_rate,
    p.promo_commission_until,
    p.created_at as partner_created_at,
    l.id as location_id, l.name as location_name, l.address as location_address, l.created_at as location_created_at
FROM partner_employees e
JOIN partners p ON e.partner_id = p.id
LEFT JOIN locations l ON e.location_id = l.id
WHERE e.id = $1
`

type GetPartnerProfileRow struct {
	EmployeeID           uuid.UUID        `json:"employee_id"`
	EmployeeName         pgtype.Text      `json:"employee_name"`
	Email                string           `json:"email"`
	Role                 string           `json:"role"`
	EmployeeCreatedAt    time.Time        `json:"employee_created_at"`
	MustChangePassword   pgtype.Bool      `json:"must_change_password"`
	PartnerID            uuid.UUID        `json:"partner_id"`
	BrandName            string           `json:"brand_name"`
	PartnerStatus        string           `json:"partner_status"`
	CommissionRate       interface{}      `json:"commission_rate"`
	PromoCommissionUntil pgtype.Date      `json:"promo_commission_until"`
	PartnerCreatedAt     time.Time        `json:"partner_created_at"`
	LocationID           pgtype.UUID      `json:"location_id"`
	LocationName         pgtype.Text      `json:"location_name"`
	LocationAddress      pgtype.Text      `json:"location_address"`
	LocationCreatedAt    pgtype.Timestamp `json:"location_created_at"`
}

func (q *Queries) GetPartnerProfile(ctx context.Context, id uuid.UUID) (GetPartnerProfileRow, error) {
	row := q.db.QueryRow(ctx, getPartnerProfile, id)
	var i GetPartnerProfileRow
	err := row.Scan(
		&i.EmployeeID,
		&i.EmployeeName,
		&i.Email,
		&i.Role,
		&i.EmployeeCreatedAt,
		&i.MustChangePassword,
		&i.PartnerID,
		&i.BrandName,
		&i.PartnerStatus,
		&i.CommissionRate,
		&i.PromoCommissionUntil,
		&i.PartnerCreatedAt,
		&i.LocationID,
		&i.LocationName,
		&i.LocationAddress,
		&i.LocationCreatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude FROM partner_applications
`

// Заявки на партнёрство
func (q *Queries) ListApplications(ctx context.Context) ([]PartnerApplication, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerApplication
	for rows.Next() {
		var i PartnerApplication
		if err := rows.Scan(
			&i.ID,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.BusinessName,
			&i.CategoryCode,
			&i.Address,
			&i.Description,
			&i.Status,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByPartnerID = `-- name: ListEmployeesByPartnerID :many
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE partner_id = $1
`

func (q *Queries) ListEmployeesByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]PartnerEmployee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByPartnerID, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerEmployee
	for rows.Next() {
		var i PartnerEmployee
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.LocationID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations
`

// Локации партнёров
func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.CategoryCode,
			&i.Name,
			&i.Address,
			&i.Location,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.WorkingHours,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerEmployees = `-- name: ListPartnerEmployees :many
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees
`

// Сотрудники партнёров
func (q *Queries) ListPartnerEmployees(ctx context.Context) ([]PartnerEmployee, error) {
	rows, err := q.db.Query(ctx, listPartnerEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerEmployee
	for rows.Next() {
		var i PartnerEmployee
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.LocationID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at FROM partners
`

// Партнёры (юридические лица)
func (q *Queries) ListPartners(ctx context.Context) ([]Partner, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.BrandName,
			&i.LogoUrl,
			&i.ParentPartnerID,
			&i.AccountType,
			&i.CommissionRate,
			&i.PromoCommissionRate,
			&i.PromoCommissionUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE partner_applications
SET status = $1, reviewed_at = $2, rejection_reason = $3
WHERE id = $4
`

type UpdateApplicationParams struct {
	Status          string             `json:"status"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.Status,
		arg.ReviewedAt,
		arg.RejectionReason,
		arg.ID,
	)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    name = COALESCE($2, name),
    address = COALESCE($3, address),
    category_code = COALESCE($4, category_code),
    logo_url = COALESCE($5, logo_url),
    cover_image_url = COALESCE($6, cover_image_url),
    working_hours = COALESCE($7, working_hours),
    gallery_urls = COALESCE($8, gallery_urls),
    updated_at = NOW()
WHERE id = $1
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type UpdateLocationParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Address       string      `json:"address"`
	CategoryCode  string      `json:"category_code"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	WorkingHours  []byte      `json:"working_hours"`
	GalleryUrls   []string    `json:"gallery_urls"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.CategoryCode,
		arg.LogoUrl,
		arg.CoverImageUrl,
		arg.WorkingHours,
		arg.GalleryUrls,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocationStatus = `-- name: UpdateLocationStatus :exec
UPDATE locations SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateLocationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error {
	_, err := q.db.Exec(ctx, updateLocationStatus, arg.ID, arg.Status)
	return err
}

const updateLocationWorkingHours = `-- name: UpdateLocationWorkingHours :exec
UPDATE locations SET working_hours = $2, updated_at = NOW() WHERE id = $1
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type UpdateLocationWorkingHoursParams struct {
	ID           uuid.UUID `json:"id"`
	WorkingHours []byte    `json:"working_hours"`
}

func (q *Queries) UpdateLocationWorkingHours(ctx context.Context, arg UpdateLocationWorkingHoursParams) error {
	_, err := q.db.Exec(ctx, updateLocationWorkingHours, arg.ID, arg.WorkingHours)
	return err
}

const updatePartner = `-- name: UpdatePartner :exec
UPDATE partners
SET brand_name = $1, logo_url = $2, parent_partner_id = $3,
    account_type = $4, commission_rate = $5, promo_commission_rate = $6,
    promo_commission_until = $7, status = $8
WHERE id = $9
`

type UpdatePartnerParams struct {
	BrandName            string         `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
	ID                   uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) error {
	_, err := q.db.Exec(ctx, updatePartner,
		arg.BrandName,
		arg.LogoUrl,
		arg.ParentPartnerID,
		arg.AccountType,
		arg.CommissionRate,
		arg.PromoCommissionRate,
		arg.PromoCommissionUntil,
		arg.Status,
		arg.ID,
	)
	return err
}

const updatePartnerEmployee = `-- name: UpdatePartnerEmployee :exec
UPDATE partner_employees
SET partner_id = $1, location_id = $2, email = $3, password_hash = $4,
    role = $5, name = $6
WHERE id = $7
`

type UpdatePartnerEmployeeParams struct {
	PartnerID    uuid.UUID   `json:"partner_id"`
	LocationID   pgtype.UUID `json:"location_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Name         pgtype.Text `json:"name"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePartnerEmployee(ctx context.Context, arg UpdatePartnerEmployeeParams) error {
	_, err := q.db.Exec(ctx, updatePartnerEmployee,
		arg.PartnerID,
		arg.LocationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
		arg.ID,
	)
	return err
}

const updatePartnerEmployeePassword = `-- name: UpdatePartnerEmployeePassword :exec
UPDATE partner_employees
SET password_hash = $1, must_change_password = $2
WHERE id = $3
`

type UpdatePartnerEmployeePasswordParams struct {
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword pgtype.Bool `json:"must_change_password"`
	ID                 uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePartnerEmployeePassword(ctx context.Context, arg UpdatePartnerEmployeePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePartnerEmployeePassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	return err
}
