// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateLocation = `-- name: ActivateLocation :exec
UPDATE locations SET status = 'active', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ActivateLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateLocation, id)
	return err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM partner_employees WHERE email = $1
    UNION
    SELECT 1 FROM partner_applications WHERE contact_email = $1 AND status = 'pending'
) AS email_exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const closeLocation = `-- name: CloseLocation :exec
UPDATE locations SET status = 'closed', updated_at = NOW() WHERE id = $1
`

func (q *Queries) CloseLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeLocation, id)
	return err
}

const countPartnerStatsOrders = `-- name: CountPartnerStatsOrders :one
SELECT COUNT(*)
FROM orders o
JOIN locations l ON o.location_id = l.id
WHERE l.partner_id = $1
  AND o.created_at >= $2
  AND o.created_at < $3::timestamptz + interval '1 day'
  AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
  AND ($5::text = '' OR o.status::text = $5::text)
`

type CountPartnerStatsOrdersParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
}

func (q *Queries) CountPartnerStatsOrders(ctx context.Context, arg CountPartnerStatsOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartnerStatsOrders,
		arg.PartnerID,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO partner_applications (
    contact_name, contact_email, contact_phone, business_name, category_code,
    address, description, status, latitude, longitude
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude, reviewed_by
`

type CreateApplicationParams struct {
	ContactName  string        `json:"contact_name"`
	ContactEmail string        `json:"contact_email"`
	ContactPhone string        `json:"contact_phone"`
	BusinessName string        `json:"business_name"`
	CategoryCode pgtype.Text   `json:"category_code"`
	Address      pgtype.Text   `json:"address"`
	Description  pgtype.Text   `json:"description"`
	Status       string        `json:"status"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (PartnerApplication, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.BusinessName,
		arg.CategoryCode,
		arg.Address,
		arg.Description,
		arg.Status,
		arg.Latitude,
		arg.Longitude,
	)
	var i PartnerApplication
	err := row.Scan(
		&i.ID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.BusinessName,
		&i.CategoryCode,
		&i.Address,
		&i.Description,
		&i.Status,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.ReviewedBy,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, address, partner_id, category_code, status, location)
VALUES ($1, $2, $3, $4, $5, ST_SetSRID(ST_MakePoint($6, $7), 4326))
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type CreateLocationParams struct {
	Name          string      `json:"name"`
	Address       string      `json:"address"`
	PartnerID     uuid.UUID   `json:"partner_id"`
	CategoryCode  string      `json:"category_code"`
	Status        string      `json:"status"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.Address,
		arg.PartnerID,
		arg.CategoryCode,
		arg.Status,
		arg.StMakepoint,
		arg.StMakepoint_2,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (
    brand_name, logo_url, parent_partner_id, account_type,
    commission_rate, promo_commission_rate, promo_commission_until, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at
`

type CreatePartnerParams struct {
	BrandName            string         `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.BrandName,
		arg.LogoUrl,
		arg.ParentPartnerID,
		arg.AccountType,
		arg.CommissionRate,
		arg.PromoCommissionRate,
		arg.PromoCommissionUntil,
		arg.Status,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerEmployee = `-- name: CreatePartnerEmployee :one
INSERT INTO partner_employees (
    partner_id, location_id, email, password_hash, role, name
) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at
`

type CreatePartnerEmployeeParams struct {
	PartnerID    uuid.UUID   `json:"partner_id"`
	LocationID   pgtype.UUID `json:"location_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Name         pgtype.Text `json:"name"`
}

func (q *Queries) CreatePartnerEmployee(ctx context.Context, arg CreatePartnerEmployeeParams) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, createPartnerEmployee,
		arg.PartnerID,
		arg.LocationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
	)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateLocation = `-- name: DeactivateLocation :exec
UPDATE locations SET status = 'inactive', updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateLocation, id)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM partner_applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deletePartnerEmployee = `-- name: DeletePartnerEmployee :exec
DELETE FROM partner_employees WHERE id = $1
`

func (q *Queries) DeletePartnerEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePartnerEmployee, id)
	return err
}

const findApplicationByID = `-- name: FindApplicationByID :one
SELECT id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude, reviewed_by FROM partner_applications WHERE id = $1
`

func (q *Queries) FindApplicationByID(ctx context.Context, id uuid.UUID) (PartnerApplication, error) {
	row := q.db.QueryRow(ctx, findApplicationByID, id)
	var i PartnerApplication
	err := row.Scan(
		&i.ID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.BusinessName,
		&i.CategoryCode,
		&i.Address,
		&i.Description,
		&i.Status,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.ReviewedBy,
	)
	return i, err
}

const findCategoryByCode = `-- name: FindCategoryByCode :one
SELECT code, name_ru, name_en, icon_url, color, sort_order FROM location_categories WHERE code = $1
`

func (q *Queries) FindCategoryByCode(ctx context.Context, code string) (LocationCategory, error) {
	row := q.db.QueryRow(ctx, findCategoryByCode, code)
	var i LocationCategory
	err := row.Scan(
		&i.Code,
		&i.NameRu,
		&i.NameEn,
		&i.IconUrl,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}

const findLocationByID = `-- name: FindLocationByID :one
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) FindLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, findLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLocationsByPartnerID = `-- name: FindLocationsByPartnerID :many
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations WHERE partner_id = $1
`

func (q *Queries) FindLocationsByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, findLocationsByPartnerID, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.CategoryCode,
			&i.Name,
			&i.Address,
			&i.Location,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.WorkingHours,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartnerByID = `-- name: FindPartnerByID :one
SELECT id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at FROM partners WHERE id = $1
`

func (q *Queries) FindPartnerByID(ctx context.Context, id uuid.UUID) (Partner, error) {
	row := q.db.QueryRow(ctx, findPartnerByID, id)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.LogoUrl,
		&i.ParentPartnerID,
		&i.AccountType,
		&i.CommissionRate,
		&i.PromoCommissionRate,
		&i.PromoCommissionUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPartnerEmployeeByEmail = `-- name: FindPartnerEmployeeByEmail :one
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE email = $1
`

func (q *Queries) FindPartnerEmployeeByEmail(ctx context.Context, email string) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, findPartnerEmployeeByEmail, email)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPartnerEmployeeByID = `-- name: FindPartnerEmployeeByID :one
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE id = $1
`

func (q *Queries) FindPartnerEmployeeByID(ctx context.Context, id uuid.UUID) (PartnerEmployee, error) {
	row := q.db.QueryRow(ctx, findPartnerEmployeeByID, id)
	var i PartnerEmployee
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.LocationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerDashboardFinance = `-- name: GetPartnerDashboardFinance :one
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $1
)
SELECT
    COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS balance_pending,
    (date_trunc('week', NOW()) + interval '1 week')::timestamptz AS next_payout_date
FROM orders o
JOIN locations l ON l.id = o.location_id
CROSS JOIN commission c
WHERE l.partner_id = $1
`

type GetPartnerDashboardFinanceRow struct {
	BalancePending int64     `json:"balance_pending"`
	NextPayoutDate time.Time `json:"next_payout_date"`
}

func (q *Queries) GetPartnerDashboardFinance(ctx context.Context, partnerID uuid.UUID) (GetPartnerDashboardFinanceRow, error) {
	row := q.db.QueryRow(ctx, getPartnerDashboardFinance, partnerID)
	var i GetPartnerDashboardFinanceRow
	err := row.Scan(&i.BalancePending, &i.NextPayoutDate)
	return i, err
}

const getPartnerDashboardTodayStats = `-- name: GetPartnerDashboardTodayStats :one
SELECT
    COUNT(*) FILTER (WHERE o.status = 'paid')::bigint AS pending_confirmation,
    COUNT(*) FILTER (WHERE o.status = 'confirmed')::bigint AS confirmed,
    COUNT(*) FILTER (WHERE o.status = 'picked_up')::bigint AS picked_up,
    COUNT(*) FILTER (WHERE o.status = 'completed')::bigint AS completed
FROM orders o
JOIN locations l ON l.id = o.location_id
WHERE l.partner_id = $1
  AND o.created_at >= date_trunc('day', NOW())
  AND o.created_at < date_trunc('day', NOW()) + interval '1 day'
`

type GetPartnerDashboardTodayStatsRow struct {
	PendingConfirmation int64 `json:"pending_confirmation"`
	Confirmed           int64 `json:"confirmed"`
	PickedUp            int64 `json:"picked_up"`
	Completed           int64 `json:"completed"`
}

func (q *Queries) GetPartnerDashboardTodayStats(ctx context.Context, partnerID uuid.UUID) (GetPartnerDashboardTodayStatsRow, error) {
	row := q.db.QueryRow(ctx, getPartnerDashboardTodayStats, partnerID)
	var i GetPartnerDashboardTodayStatsRow
	err := row.Scan(
		&i.PendingConfirmation,
		&i.Confirmed,
		&i.PickedUp,
		&i.Completed,
	)
	return i, err
}

const getPartnerDashboardWeekStats = `-- name: GetPartnerDashboardWeekStats :one
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $1
),
order_stats AS (
    SELECT
        COUNT(*) FILTER (WHERE o.status = 'completed')::bigint AS orders_completed,
        COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0)::bigint AS gross_revenue,
        COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS net_revenue
    FROM orders o
    JOIN locations l ON l.id = o.location_id
    CROSS JOIN commission c
    WHERE l.partner_id = $1
      AND o.created_at >= NOW() - interval '7 days'
),
review_stats AS (
    SELECT COALESCE(AVG(r.rating), 0)::double precision AS avg_rating
    FROM reviews r
    JOIN locations l ON l.id = r.location_id
    WHERE l.partner_id = $1
      AND r.created_at >= NOW() - interval '7 days'
)
SELECT
    order_stats.orders_completed,
    order_stats.gross_revenue,
    order_stats.net_revenue,
    review_stats.avg_rating
FROM order_stats, review_stats
`

type GetPartnerDashboardWeekStatsRow struct {
	OrdersCompleted int64   `json:"orders_completed"`
	GrossRevenue    int64   `json:"gross_revenue"`
	NetRevenue      int64   `json:"net_revenue"`
	AvgRating       float64 `json:"avg_rating"`
}

func (q *Queries) GetPartnerDashboardWeekStats(ctx context.Context, id uuid.UUID) (GetPartnerDashboardWeekStatsRow, error) {
	row := q.db.QueryRow(ctx, getPartnerDashboardWeekStats, id)
	var i GetPartnerDashboardWeekStatsRow
	err := row.Scan(
		&i.OrdersCompleted,
		&i.GrossRevenue,
		&i.NetRevenue,
		&i.AvgRating,
	)
	return i, err
}

const getPartnerProfile = `-- name: GetPartnerProfile :one
SELECT
    e.id as employee_id, e.name as employee_name, e.email, e.role, e.created_at as employee_created_at, e.must_change_password,
    p.id as partner_id, p.brand_name, p.status as partner_status,
    CASE
        WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
        ELSE p.commission_rate
    END AS commission_rate,
    p.promo_commission_until,
    p.created_at as partner_created_at,
    l.id as location_id, l.name as location_name, l.address as location_address, l.created_at as location_created_at
FROM partner_employees e
JOIN partners p ON e.partner_id = p.id
LEFT JOIN locations l ON e.location_id = l.id
WHERE e.id = $1
`

type GetPartnerProfileRow struct {
	EmployeeID           uuid.UUID        `json:"employee_id"`
	EmployeeName         pgtype.Text      `json:"employee_name"`
	Email                string           `json:"email"`
	Role                 string           `json:"role"`
	EmployeeCreatedAt    time.Time        `json:"employee_created_at"`
	MustChangePassword   pgtype.Bool      `json:"must_change_password"`
	PartnerID            uuid.UUID        `json:"partner_id"`
	BrandName            string           `json:"brand_name"`
	PartnerStatus        string           `json:"partner_status"`
	CommissionRate       interface{}      `json:"commission_rate"`
	PromoCommissionUntil pgtype.Date      `json:"promo_commission_until"`
	PartnerCreatedAt     time.Time        `json:"partner_created_at"`
	LocationID           pgtype.UUID      `json:"location_id"`
	LocationName         pgtype.Text      `json:"location_name"`
	LocationAddress      pgtype.Text      `json:"location_address"`
	LocationCreatedAt    pgtype.Timestamp `json:"location_created_at"`
}

func (q *Queries) GetPartnerProfile(ctx context.Context, id uuid.UUID) (GetPartnerProfileRow, error) {
	row := q.db.QueryRow(ctx, getPartnerProfile, id)
	var i GetPartnerProfileRow
	err := row.Scan(
		&i.EmployeeID,
		&i.EmployeeName,
		&i.Email,
		&i.Role,
		&i.EmployeeCreatedAt,
		&i.MustChangePassword,
		&i.PartnerID,
		&i.BrandName,
		&i.PartnerStatus,
		&i.CommissionRate,
		&i.PromoCommissionUntil,
		&i.PartnerCreatedAt,
		&i.LocationID,
		&i.LocationName,
		&i.LocationAddress,
		&i.LocationCreatedAt,
	)
	return i, err
}

const getPartnerStatsStatusBreakdown = `-- name: GetPartnerStatsStatusBreakdown :many
WITH totals AS (
    SELECT COUNT(*)::double precision AS total_count
    FROM orders o
    JOIN locations l ON l.id = o.location_id
    WHERE l.partner_id = $1
      AND o.created_at >= $2
      AND o.created_at < $3::timestamptz + interval '1 day'
      AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
      AND ($5::text = '' OR o.status::text = $5::text)
)
SELECT
    o.status::text AS status,
    COUNT(*)::bigint AS count,
    CASE
        WHEN totals.total_count = 0 THEN 0::double precision
        ELSE COUNT(*)::double precision / totals.total_count
    END::double precision AS share
FROM orders o
JOIN locations l ON l.id = o.location_id
CROSS JOIN totals
WHERE l.partner_id = $1
  AND o.created_at >= $2
  AND o.created_at < $3::timestamptz + interval '1 day'
  AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
  AND ($5::text = '' OR o.status::text = $5::text)
GROUP BY o.status, totals.total_count
ORDER BY count DESC, o.status::text ASC
`

type GetPartnerStatsStatusBreakdownParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
}

type GetPartnerStatsStatusBreakdownRow struct {
	Status string  `json:"status"`
	Count  int64   `json:"count"`
	Share  float64 `json:"share"`
}

func (q *Queries) GetPartnerStatsStatusBreakdown(ctx context.Context, arg GetPartnerStatsStatusBreakdownParams) ([]GetPartnerStatsStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getPartnerStatsStatusBreakdown,
		arg.PartnerID,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartnerStatsStatusBreakdownRow
	for rows.Next() {
		var i GetPartnerStatsStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count, &i.Share); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartnerStatsSummary = `-- name: GetPartnerStatsSummary :one
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $1
),
order_stats AS (
    SELECT
        COUNT(*)::bigint AS orders_total,
        COUNT(*) FILTER (WHERE o.status = 'completed')::bigint AS orders_completed,
        COUNT(*) FILTER (WHERE o.status = 'cancelled')::bigint AS orders_cancelled,
        COUNT(*) FILTER (WHERE o.status = 'paid')::bigint AS orders_pending_confirmation,
        COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0)::bigint AS gross_revenue,
        COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS net_revenue,
        COALESCE(AVG(o.amount) FILTER (WHERE o.status = 'completed'), 0)::double precision AS avg_order_value
    FROM orders o
    JOIN locations l ON l.id = o.location_id
    CROSS JOIN commission c
    WHERE l.partner_id = $1
      AND o.created_at >= $2
      AND o.created_at < $3::timestamptz + interval '1 day'
      AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
      AND ($5::text = '' OR o.status::text = $5::text)
),
review_stats AS (
    SELECT
        COALESCE(AVG(r.rating), 0)::double precision AS avg_rating,
        COUNT(*)::bigint AS reviews_count
    FROM reviews r
    JOIN locations l ON l.id = r.location_id
    WHERE l.partner_id = $1
      AND r.created_at >= $2
      AND r.created_at < $3::timestamptz + interval '1 day'
      AND ($4::uuid IS NULL OR r.location_id = $4::uuid)
)
SELECT
    order_stats.orders_total,
    order_stats.orders_completed,
    order_stats.orders_cancelled,
    order_stats.orders_pending_confirmation,
    order_stats.gross_revenue,
    order_stats.net_revenue,
    order_stats.avg_order_value,
    review_stats.avg_rating,
    review_stats.reviews_count
FROM order_stats, review_stats
`

type GetPartnerStatsSummaryParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
}

type GetPartnerStatsSummaryRow struct {
	OrdersTotal               int64   `json:"orders_total"`
	OrdersCompleted           int64   `json:"orders_completed"`
	OrdersCancelled           int64   `json:"orders_cancelled"`
	OrdersPendingConfirmation int64   `json:"orders_pending_confirmation"`
	GrossRevenue              int64   `json:"gross_revenue"`
	NetRevenue                int64   `json:"net_revenue"`
	AvgOrderValue             float64 `json:"avg_order_value"`
	AvgRating                 float64 `json:"avg_rating"`
	ReviewsCount              int64   `json:"reviews_count"`
}

func (q *Queries) GetPartnerStatsSummary(ctx context.Context, arg GetPartnerStatsSummaryParams) (GetPartnerStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPartnerStatsSummary,
		arg.PartnerID,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
	)
	var i GetPartnerStatsSummaryRow
	err := row.Scan(
		&i.OrdersTotal,
		&i.OrdersCompleted,
		&i.OrdersCancelled,
		&i.OrdersPendingConfirmation,
		&i.GrossRevenue,
		&i.NetRevenue,
		&i.AvgOrderValue,
		&i.AvgRating,
		&i.ReviewsCount,
	)
	return i, err
}

const getPartnerStatsTimeline = `-- name: GetPartnerStatsTimeline :many
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $1
),
series AS (
    SELECT generate_series($2::timestamptz, $3::timestamptz, interval '1 day') AS day
),
aggregated AS (
    SELECT
        date_trunc('day', o.created_at) AS day,
        COUNT(*)::bigint AS orders_total,
        COUNT(*) FILTER (WHERE o.status = 'completed')::bigint AS orders_completed,
        COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0)::bigint AS gross_revenue,
        COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS net_revenue
    FROM orders o
    JOIN locations l ON l.id = o.location_id
    CROSS JOIN commission c
    WHERE l.partner_id = $1
      AND o.created_at >= $2
      AND o.created_at < $3::timestamptz + interval '1 day'
      AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
      AND ($5::text = '' OR o.status::text = $5::text)
    GROUP BY 1
)
SELECT
    series.day::timestamptz AS date,
    COALESCE(aggregated.orders_total, 0)::bigint AS orders_total,
    COALESCE(aggregated.orders_completed, 0)::bigint AS orders_completed,
    COALESCE(aggregated.gross_revenue, 0)::bigint AS gross_revenue,
    COALESCE(aggregated.net_revenue, 0)::bigint AS net_revenue
FROM series
LEFT JOIN aggregated ON aggregated.day = series.day
ORDER BY series.day ASC
`

type GetPartnerStatsTimelineParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
}

type GetPartnerStatsTimelineRow struct {
	Date            time.Time `json:"date"`
	OrdersTotal     int64     `json:"orders_total"`
	OrdersCompleted int64     `json:"orders_completed"`
	GrossRevenue    int64     `json:"gross_revenue"`
	NetRevenue      int64     `json:"net_revenue"`
}

func (q *Queries) GetPartnerStatsTimeline(ctx context.Context, arg GetPartnerStatsTimelineParams) ([]GetPartnerStatsTimelineRow, error) {
	rows, err := q.db.Query(ctx, getPartnerStatsTimeline,
		arg.PartnerID,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartnerStatsTimelineRow
	for rows.Next() {
		var i GetPartnerStatsTimelineRow
		if err := rows.Scan(
			&i.Date,
			&i.OrdersTotal,
			&i.OrdersCompleted,
			&i.GrossRevenue,
			&i.NetRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartnerStatsTopBoxes = `-- name: GetPartnerStatsTopBoxes :many
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $5
)
SELECT
    sb.id AS box_id,
    sb.name,
    COALESCE(sb.image_url, '') AS image_url,
    l.name AS location_name,
    COUNT(o.id)::bigint AS orders_total,
    COUNT(o.id) FILTER (WHERE o.status = 'completed')::bigint AS orders_completed,
    COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0)::bigint AS gross_revenue,
    COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS net_revenue
FROM surprise_boxes sb
JOIN locations l ON l.id = sb.location_id
LEFT JOIN orders o ON o.box_id = sb.id
    AND o.created_at >= $1
    AND o.created_at < $2::timestamptz + interval '1 day'
    AND ($3::uuid IS NULL OR o.location_id = $3::uuid)
    AND ($4::text = '' OR o.status::text = $4::text)
CROSS JOIN commission c
WHERE l.partner_id = $5
  AND ($3::uuid IS NULL OR l.id = $3::uuid)
GROUP BY sb.id, sb.name, sb.image_url, l.name
ORDER BY
    CASE WHEN $6::text = 'revenue_desc' THEN COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0) END DESC,
    CASE WHEN $6::text = 'orders_desc' THEN COUNT(o.id) END DESC,
    CASE WHEN $6::text = 'name_asc' THEN sb.name END ASC,
    sb.name ASC
`

type GetPartnerStatsTopBoxesParams struct {
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
	PartnerID  uuid.UUID   `json:"partner_id"`
	Sort       string      `json:"sort"`
}

type GetPartnerStatsTopBoxesRow struct {
	BoxID           uuid.UUID `json:"box_id"`
	Name            string    `json:"name"`
	ImageUrl        string    `json:"image_url"`
	LocationName    string    `json:"location_name"`
	OrdersTotal     int64     `json:"orders_total"`
	OrdersCompleted int64     `json:"orders_completed"`
	GrossRevenue    int64     `json:"gross_revenue"`
	NetRevenue      int64     `json:"net_revenue"`
}

func (q *Queries) GetPartnerStatsTopBoxes(ctx context.Context, arg GetPartnerStatsTopBoxesParams) ([]GetPartnerStatsTopBoxesRow, error) {
	rows, err := q.db.Query(ctx, getPartnerStatsTopBoxes,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
		arg.PartnerID,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartnerStatsTopBoxesRow
	for rows.Next() {
		var i GetPartnerStatsTopBoxesRow
		if err := rows.Scan(
			&i.BoxID,
			&i.Name,
			&i.ImageUrl,
			&i.LocationName,
			&i.OrdersTotal,
			&i.OrdersCompleted,
			&i.GrossRevenue,
			&i.NetRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartnerStatsTopLocations = `-- name: GetPartnerStatsTopLocations :many
WITH commission AS (
    SELECT
        CASE
            WHEN p.promo_commission_until >= NOW() THEN COALESCE(p.promo_commission_rate, p.commission_rate)
            ELSE p.commission_rate
        END AS rate
    FROM partners p
    WHERE p.id = $4
),
review_stats AS (
    SELECT
        r.location_id,
        COALESCE(AVG(r.rating), 0)::double precision AS avg_rating
    FROM reviews r
    JOIN locations l ON l.id = r.location_id
    WHERE l.partner_id = $4
      AND r.created_at >= $1
      AND r.created_at < $2::timestamptz + interval '1 day'
      AND ($5::uuid IS NULL OR r.location_id = $5::uuid)
    GROUP BY r.location_id
)
SELECT
    l.id AS location_id,
    l.name,
    l.address,
    COUNT(o.id)::bigint AS orders_total,
    COUNT(o.id) FILTER (WHERE o.status = 'completed')::bigint AS orders_completed,
    COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0)::bigint AS gross_revenue,
    COALESCE(SUM(o.amount * (1 - c.rate)) FILTER (WHERE o.status = 'completed'), 0)::bigint AS net_revenue,
    COALESCE(review_stats.avg_rating, 0)::double precision AS avg_rating
FROM locations l
LEFT JOIN orders o ON o.location_id = l.id
    AND o.created_at >= $1
    AND o.created_at < $2::timestamptz + interval '1 day'
    AND ($3::text = '' OR o.status::text = $3::text)
CROSS JOIN commission c
LEFT JOIN review_stats ON review_stats.location_id = l.id
WHERE l.partner_id = $4
  AND ($5::uuid IS NULL OR l.id = $5::uuid)
GROUP BY l.id, l.name, l.address, review_stats.avg_rating
ORDER BY
    CASE WHEN $6::text = 'revenue_desc' THEN COALESCE(SUM(o.amount) FILTER (WHERE o.status = 'completed'), 0) END DESC,
    CASE WHEN $6::text = 'orders_desc' THEN COUNT(o.id) END DESC,
    CASE WHEN $6::text = 'rating_desc' THEN COALESCE(review_stats.avg_rating, 0) END DESC,
    CASE WHEN $6::text = 'name_asc' THEN l.name END ASC,
    l.name ASC
`

type GetPartnerStatsTopLocationsParams struct {
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	Status     string      `json:"status"`
	PartnerID  uuid.UUID   `json:"partner_id"`
	LocationID pgtype.UUID `json:"location_id"`
	Sort       string      `json:"sort"`
}

type GetPartnerStatsTopLocationsRow struct {
	LocationID      uuid.UUID `json:"location_id"`
	Name            string    `json:"name"`
	Address         string    `json:"address"`
	OrdersTotal     int64     `json:"orders_total"`
	OrdersCompleted int64     `json:"orders_completed"`
	GrossRevenue    int64     `json:"gross_revenue"`
	NetRevenue      int64     `json:"net_revenue"`
	AvgRating       float64   `json:"avg_rating"`
}

func (q *Queries) GetPartnerStatsTopLocations(ctx context.Context, arg GetPartnerStatsTopLocationsParams) ([]GetPartnerStatsTopLocationsRow, error) {
	rows, err := q.db.Query(ctx, getPartnerStatsTopLocations,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.PartnerID,
		arg.LocationID,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartnerStatsTopLocationsRow
	for rows.Next() {
		var i GetPartnerStatsTopLocationsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.Address,
			&i.OrdersTotal,
			&i.OrdersCompleted,
			&i.GrossRevenue,
			&i.NetRevenue,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT id, contact_name, contact_email, contact_phone, business_name, category_code, address, description, status, reviewed_at, rejection_reason, created_at, latitude, longitude, reviewed_by FROM partner_applications
`

// Заявки на партнёрство
func (q *Queries) ListApplications(ctx context.Context) ([]PartnerApplication, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerApplication
	for rows.Next() {
		var i PartnerApplication
		if err := rows.Scan(
			&i.ID,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.BusinessName,
			&i.CategoryCode,
			&i.Address,
			&i.Description,
			&i.Status,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByPartnerID = `-- name: ListEmployeesByPartnerID :many
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees WHERE partner_id = $1
`

func (q *Queries) ListEmployeesByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]PartnerEmployee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByPartnerID, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerEmployee
	for rows.Next() {
		var i PartnerEmployee
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.LocationID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at FROM locations
`

// Локации партнёров
func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.CategoryCode,
			&i.Name,
			&i.Address,
			&i.Location,
			&i.Phone,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.WorkingHours,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerEmployees = `-- name: ListPartnerEmployees :many
SELECT id, partner_id, location_id, email, password_hash, role, name, must_change_password, last_login_at, created_at, updated_at FROM partner_employees
`

// Сотрудники партнёров
func (q *Queries) ListPartnerEmployees(ctx context.Context) ([]PartnerEmployee, error) {
	rows, err := q.db.Query(ctx, listPartnerEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerEmployee
	for rows.Next() {
		var i PartnerEmployee
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.LocationID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerStatsOrders = `-- name: ListPartnerStatsOrders :many
SELECT
  o.id,
  o.status,
  o.pickup_code,
  o.amount,
  o.created_at,
  sb.name AS box_name,
  COALESCE(sb.image_url, '') AS box_image_url,
  COALESCE(u.phone, '') AS customer_phone,
  COALESCE(u.name, '') AS customer_name,
  l.id AS location_id,
  l.name AS location_name,
  l.address AS location_address,
  o.pickup_time_start,
  o.pickup_time_end
FROM orders o
JOIN surprise_boxes sb ON o.box_id = sb.id
JOIN users u ON o.user_id = u.id
JOIN locations l ON o.location_id = l.id
WHERE l.partner_id = $1
  AND o.created_at >= $2
  AND o.created_at < $3::timestamptz + interval '1 day'
  AND ($4::uuid IS NULL OR o.location_id = $4::uuid)
  AND ($5::text = '' OR o.status::text = $5::text)
ORDER BY
  CASE WHEN $6::text = 'created_at_desc' THEN o.created_at END DESC,
  CASE WHEN $6::text = 'created_at_asc' THEN o.created_at END ASC,
  CASE WHEN $6::text = 'amount_desc' THEN o.amount END DESC,
  CASE WHEN $6::text = 'amount_asc' THEN o.amount END ASC,
  CASE WHEN $6::text = 'pickup_time_desc' THEN o.pickup_time_start END DESC,
  CASE WHEN $6::text = 'pickup_time_asc' THEN o.pickup_time_start END ASC,
  o.created_at DESC
LIMIT $8 OFFSET $7
`

type ListPartnerStatsOrdersParams struct {
	PartnerID  uuid.UUID   `json:"partner_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	LocationID pgtype.UUID `json:"location_id"`
	Status     string      `json:"status"`
	Sort       string      `json:"sort"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListPartnerStatsOrdersRow struct {
	ID              uuid.UUID      `json:"id"`
	Status          OrderStatus    `json:"status"`
	PickupCode      string         `json:"pickup_code"`
	Amount          pgtype.Numeric `json:"amount"`
	CreatedAt       time.Time      `json:"created_at"`
	BoxName         string         `json:"box_name"`
	BoxImageUrl     string         `json:"box_image_url"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerName    string         `json:"customer_name"`
	LocationID      uuid.UUID      `json:"location_id"`
	LocationName    string         `json:"location_name"`
	LocationAddress string         `json:"location_address"`
	PickupTimeStart time.Time      `json:"pickup_time_start"`
	PickupTimeEnd   time.Time      `json:"pickup_time_end"`
}

func (q *Queries) ListPartnerStatsOrders(ctx context.Context, arg ListPartnerStatsOrdersParams) ([]ListPartnerStatsOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPartnerStatsOrders,
		arg.PartnerID,
		arg.StartDate,
		arg.EndDate,
		arg.LocationID,
		arg.Status,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerStatsOrdersRow
	for rows.Next() {
		var i ListPartnerStatsOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PickupCode,
			&i.Amount,
			&i.CreatedAt,
			&i.BoxName,
			&i.BoxImageUrl,
			&i.CustomerPhone,
			&i.CustomerName,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.PickupTimeStart,
			&i.PickupTimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, brand_name, logo_url, parent_partner_id, account_type, commission_rate, promo_commission_rate, promo_commission_until, status, created_at, updated_at FROM partners
`

// Партнёры (юридические лица)
func (q *Queries) ListPartners(ctx context.Context) ([]Partner, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.BrandName,
			&i.LogoUrl,
			&i.ParentPartnerID,
			&i.AccountType,
			&i.CommissionRate,
			&i.PromoCommissionRate,
			&i.PromoCommissionUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewApplication = `-- name: ReviewApplication :exec
UPDATE partner_applications
SET status           = $1,
    reviewed_at      = NOW(),
    rejection_reason = $2,
    reviewed_by      = $3
WHERE id = $4
`

type ReviewApplicationParams struct {
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) ReviewApplication(ctx context.Context, arg ReviewApplicationParams) error {
	_, err := q.db.Exec(ctx, reviewApplication,
		arg.Status,
		arg.RejectionReason,
		arg.ReviewedBy,
		arg.ID,
	)
	return err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE partner_applications
SET status = $1, reviewed_at = $2, rejection_reason = $3
WHERE id = $4
`

type UpdateApplicationParams struct {
	Status          string             `json:"status"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.Status,
		arg.ReviewedAt,
		arg.RejectionReason,
		arg.ID,
	)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    name = COALESCE($2, name),
    address = COALESCE($3, address),
    category_code = COALESCE($4, category_code),
    logo_url = COALESCE($5, logo_url),
    cover_image_url = COALESCE($6, cover_image_url),
    working_hours = COALESCE($7, working_hours),
    gallery_urls = COALESCE($8, gallery_urls),
    phone = COALESCE($9, phone),
    updated_at = NOW()
WHERE id = $1
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type UpdateLocationParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Address       string      `json:"address"`
	CategoryCode  string      `json:"category_code"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	WorkingHours  []byte      `json:"working_hours"`
	GalleryUrls   []string    `json:"gallery_urls"`
	Phone         pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.CategoryCode,
		arg.LogoUrl,
		arg.CoverImageUrl,
		arg.WorkingHours,
		arg.GalleryUrls,
		arg.Phone,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.CategoryCode,
		&i.Name,
		&i.Address,
		&i.Location,
		&i.Phone,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.WorkingHours,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocationStatus = `-- name: UpdateLocationStatus :exec
UPDATE locations SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateLocationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error {
	_, err := q.db.Exec(ctx, updateLocationStatus, arg.ID, arg.Status)
	return err
}

const updateLocationWorkingHours = `-- name: UpdateLocationWorkingHours :exec
UPDATE locations SET working_hours = $2, updated_at = NOW() WHERE id = $1
RETURNING id, partner_id, category_code, name, address, location, phone, logo_url, cover_image_url, gallery_urls, working_hours, status, created_at, updated_at
`

type UpdateLocationWorkingHoursParams struct {
	ID           uuid.UUID `json:"id"`
	WorkingHours []byte    `json:"working_hours"`
}

func (q *Queries) UpdateLocationWorkingHours(ctx context.Context, arg UpdateLocationWorkingHoursParams) error {
	_, err := q.db.Exec(ctx, updateLocationWorkingHours, arg.ID, arg.WorkingHours)
	return err
}

const updatePartner = `-- name: UpdatePartner :exec
UPDATE partners
SET brand_name = $1, logo_url = $2, parent_partner_id = $3,
    account_type = $4, commission_rate = $5, promo_commission_rate = $6,
    promo_commission_until = $7, status = $8
WHERE id = $9
`

type UpdatePartnerParams struct {
	BrandName            string         `json:"brand_name"`
	LogoUrl              pgtype.Text    `json:"logo_url"`
	ParentPartnerID      pgtype.UUID    `json:"parent_partner_id"`
	AccountType          pgtype.Text    `json:"account_type"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
	Status               string         `json:"status"`
	ID                   uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) error {
	_, err := q.db.Exec(ctx, updatePartner,
		arg.BrandName,
		arg.LogoUrl,
		arg.ParentPartnerID,
		arg.AccountType,
		arg.CommissionRate,
		arg.PromoCommissionRate,
		arg.PromoCommissionUntil,
		arg.Status,
		arg.ID,
	)
	return err
}

const updatePartnerEmployee = `-- name: UpdatePartnerEmployee :exec
UPDATE partner_employees
SET partner_id = $1, location_id = $2, email = $3, password_hash = $4,
    role = $5, name = $6
WHERE id = $7
`

type UpdatePartnerEmployeeParams struct {
	PartnerID    uuid.UUID   `json:"partner_id"`
	LocationID   pgtype.UUID `json:"location_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Name         pgtype.Text `json:"name"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePartnerEmployee(ctx context.Context, arg UpdatePartnerEmployeeParams) error {
	_, err := q.db.Exec(ctx, updatePartnerEmployee,
		arg.PartnerID,
		arg.LocationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
		arg.ID,
	)
	return err
}

const updatePartnerEmployeeName = `-- name: UpdatePartnerEmployeeName :exec
UPDATE partner_employees
SET name = $1
WHERE id = $2
`

type UpdatePartnerEmployeeNameParams struct {
	Name pgtype.Text `json:"name"`
	ID   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePartnerEmployeeName(ctx context.Context, arg UpdatePartnerEmployeeNameParams) error {
	_, err := q.db.Exec(ctx, updatePartnerEmployeeName, arg.Name, arg.ID)
	return err
}

const updatePartnerEmployeePassword = `-- name: UpdatePartnerEmployeePassword :exec
UPDATE partner_employees
SET password_hash = $1, must_change_password = $2
WHERE id = $3
`

type UpdatePartnerEmployeePasswordParams struct {
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword pgtype.Bool `json:"must_change_password"`
	ID                 uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePartnerEmployeePassword(ctx context.Context, arg UpdatePartnerEmployeePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePartnerEmployeePassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	return err
}

const updatePartnerStatusByID = `-- name: UpdatePartnerStatusByID :exec
UPDATE partners
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePartnerStatusByIDParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePartnerStatusByID(ctx context.Context, arg UpdatePartnerStatusByIDParams) error {
	_, err := q.db.Exec(ctx, updatePartnerStatusByID, arg.ID, arg.Status)
	return err
}

const upsertPartnerLegalInfo = `-- name: UpsertPartnerLegalInfo :one
INSERT INTO partner_legal_info (
    partner_id, inn, ogrn, kpp, legal_address, legal_name
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (partner_id)
DO UPDATE SET
    inn = EXCLUDED.inn,
    ogrn = EXCLUDED.ogrn,
    kpp = EXCLUDED.kpp,
    legal_address = EXCLUDED.legal_address,
    legal_name = EXCLUDED.legal_name,
    verification_status = 'pending',
    verification_comment = NULL,
    verified_by = NULL,
    verified_at = NULL,
    updated_at = NOW()
RETURNING partner_id, inn, ogrn, kpp, legal_address, created_at, updated_at, legal_name, verification_status, verification_comment, verified_by, verified_at
`

type UpsertPartnerLegalInfoParams struct {
	PartnerID    uuid.UUID   `json:"partner_id"`
	Inn          string      `json:"inn"`
	Ogrn         pgtype.Text `json:"ogrn"`
	Kpp          pgtype.Text `json:"kpp"`
	LegalAddress string      `json:"legal_address"`
	LegalName    string      `json:"legal_name"`
}

func (q *Queries) UpsertPartnerLegalInfo(ctx context.Context, arg UpsertPartnerLegalInfoParams) (PartnerLegalInfo, error) {
	row := q.db.QueryRow(ctx, upsertPartnerLegalInfo,
		arg.PartnerID,
		arg.Inn,
		arg.Ogrn,
		arg.Kpp,
		arg.LegalAddress,
		arg.LegalName,
	)
	var i PartnerLegalInfo
	err := row.Scan(
		&i.PartnerID,
		&i.Inn,
		&i.Ogrn,
		&i.Kpp,
		&i.LegalAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.VerificationStatus,
		&i.VerificationComment,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}
