// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id, provider_payment_id, payment_url, method, provider, amount, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, provider_payment_id, payment_url, method, provider, amount, status, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID           uuid.UUID           `json:"order_id"`
	ProviderPaymentID pgtype.Text         `json:"provider_payment_id"`
	PaymentUrl        pgtype.Text         `json:"payment_url"`
	Method            NullPaymentMethod   `json:"method"`
	Provider          NullPaymentProvider `json:"provider"`
	Amount            pgtype.Numeric      `json:"amount"`
	Status            PaymentStatus       `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.ProviderPaymentID,
		arg.PaymentUrl,
		arg.Method,
		arg.Provider,
		arg.Amount,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Method,
		&i.Provider,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, provider_payment_id, payment_url, method, provider, amount, status, paid_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Method,
		&i.Provider,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, provider_payment_id, payment_url, method, provider, amount, status, paid_at, created_at, updated_at FROM payments WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Method,
		&i.Provider,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET
    status = $2,
    paid_at = COALESCE($3, paid_at)
WHERE id = $1 RETURNING id, order_id, provider_payment_id, payment_url, method, provider, amount, status, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status PaymentStatus      `json:"status"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.PaidAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Method,
		&i.Provider,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
