// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payout.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPayoutOrder = `-- name: AddPayoutOrder :exec
INSERT INTO partner_payout_orders (payout_id, order_id, order_amount, commission_part)
VALUES ($1, $2, $3, $4)
`

type AddPayoutOrderParams struct {
	PayoutID       uuid.UUID      `json:"payout_id"`
	OrderID        uuid.UUID      `json:"order_id"`
	OrderAmount    pgtype.Numeric `json:"order_amount"`
	CommissionPart pgtype.Numeric `json:"commission_part"`
}

func (q *Queries) AddPayoutOrder(ctx context.Context, arg AddPayoutOrderParams) error {
	_, err := q.db.Exec(ctx, addPayoutOrder,
		arg.PayoutID,
		arg.OrderID,
		arg.OrderAmount,
		arg.CommissionPart,
	)
	return err
}

const countPayoutsByPartner = `-- name: CountPayoutsByPartner :one
SELECT COUNT(*)::bigint FROM partner_payouts WHERE partner_id = $1
`

func (q *Queries) CountPayoutsByPartner(ctx context.Context, partnerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutsByPartner, partnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPayout = `-- name: CreatePayout :one

INSERT INTO partner_payouts (
    id, partner_id, period_start, period_end,
    gross_amount, commission_amount, commission_rate_applied, net_amount,
    status, provider, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, partner_id, period_start, period_end, gross_amount, commission_amount, commission_rate_applied, net_amount, status, provider, provider_payout_id, idempotency_key, error_message, processed_at, created_at, updated_at
`

type CreatePayoutParams struct {
	ID                    uuid.UUID      `json:"id"`
	PartnerID             uuid.UUID      `json:"partner_id"`
	PeriodStart           time.Time      `json:"period_start"`
	PeriodEnd             time.Time      `json:"period_end"`
	GrossAmount           pgtype.Numeric `json:"gross_amount"`
	CommissionAmount      pgtype.Numeric `json:"commission_amount"`
	CommissionRateApplied pgtype.Numeric `json:"commission_rate_applied"`
	NetAmount             pgtype.Numeric `json:"net_amount"`
	Status                string         `json:"status"`
	Provider              string         `json:"provider"`
	IdempotencyKey        pgtype.Text    `json:"idempotency_key"`
}

// Создание выплаты и связки с заказами
func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (PartnerPayout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.ID,
		arg.PartnerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.GrossAmount,
		arg.CommissionAmount,
		arg.CommissionRateApplied,
		arg.NetAmount,
		arg.Status,
		arg.Provider,
		arg.IdempotencyKey,
	)
	var i PartnerPayout
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GrossAmount,
		&i.CommissionAmount,
		&i.CommissionRateApplied,
		&i.NetAmount,
		&i.Status,
		&i.Provider,
		&i.ProviderPayoutID,
		&i.IdempotencyKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, partner_id, period_start, period_end, gross_amount, commission_amount, commission_rate_applied, net_amount, status, provider, provider_payout_id, idempotency_key, error_message, processed_at, created_at, updated_at FROM partner_payouts WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id uuid.UUID) (PartnerPayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i PartnerPayout
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GrossAmount,
		&i.CommissionAmount,
		&i.CommissionRateApplied,
		&i.NetAmount,
		&i.Status,
		&i.Provider,
		&i.ProviderPayoutID,
		&i.IdempotencyKey,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutDestination = `-- name: GetPayoutDestination :one

SELECT partner_id, type, sbp_phone, sbp_bank_id, recipient_name, created_at, updated_at FROM partner_payout_destinations WHERE partner_id = $1
`

// Реквизиты получателя выплат
func (q *Queries) GetPayoutDestination(ctx context.Context, partnerID uuid.UUID) (PartnerPayoutDestination, error) {
	row := q.db.QueryRow(ctx, getPayoutDestination, partnerID)
	var i PartnerPayoutDestination
	err := row.Scan(
		&i.PartnerID,
		&i.Type,
		&i.SbpPhone,
		&i.SbpBankID,
		&i.RecipientName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePartnersForPayout = `-- name: ListActivePartnersForPayout :many

SELECT id, commission_rate, promo_commission_rate, promo_commission_until
FROM partners
WHERE status = 'active'
ORDER BY id
`

type ListActivePartnersForPayoutRow struct {
	ID                   uuid.UUID      `json:"id"`
	CommissionRate       pgtype.Numeric `json:"commission_rate"`
	PromoCommissionRate  pgtype.Numeric `json:"promo_commission_rate"`
	PromoCommissionUntil pgtype.Date    `json:"promo_commission_until"`
}

// Активные партнёры с тарифной информацией для воркера расчёта
func (q *Queries) ListActivePartnersForPayout(ctx context.Context) ([]ListActivePartnersForPayoutRow, error) {
	rows, err := q.db.Query(ctx, listActivePartnersForPayout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePartnersForPayoutRow
	for rows.Next() {
		var i ListActivePartnersForPayoutRow
		if err := rows.Scan(
			&i.ID,
			&i.CommissionRate,
			&i.PromoCommissionRate,
			&i.PromoCommissionUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutOrders = `-- name: ListPayoutOrders :many
SELECT payout_id, order_id, order_amount, commission_part FROM partner_payout_orders WHERE payout_id = $1
`

func (q *Queries) ListPayoutOrders(ctx context.Context, payoutID uuid.UUID) ([]PartnerPayoutOrder, error) {
	rows, err := q.db.Query(ctx, listPayoutOrders, payoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerPayoutOrder
	for rows.Next() {
		var i PartnerPayoutOrder
		if err := rows.Scan(
			&i.PayoutID,
			&i.OrderID,
			&i.OrderAmount,
			&i.CommissionPart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByPartner = `-- name: ListPayoutsByPartner :many

SELECT id, partner_id, period_start, period_end, gross_amount, commission_amount, commission_rate_applied, net_amount, status, provider, provider_payout_id, idempotency_key, error_message, processed_at, created_at, updated_at FROM partner_payouts
WHERE partner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsByPartnerParams struct {
	PartnerID uuid.UUID `json:"partner_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

// История выплат партнёра
func (q *Queries) ListPayoutsByPartner(ctx context.Context, arg ListPayoutsByPartnerParams) ([]PartnerPayout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByPartner, arg.PartnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerPayout
	for rows.Next() {
		var i PartnerPayout
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.GrossAmount,
			&i.CommissionAmount,
			&i.CommissionRateApplied,
			&i.NetAmount,
			&i.Status,
			&i.Provider,
			&i.ProviderPayoutID,
			&i.IdempotencyKey,
			&i.ErrorMessage,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingPayouts = `-- name: ListProcessingPayouts :many
SELECT id, provider_payout_id
FROM partner_payouts
WHERE status = 'processing'
  AND provider_payout_id IS NOT NULL
ORDER BY created_at ASC
LIMIT $1
`

type ListProcessingPayoutsRow struct {
	ID               uuid.UUID   `json:"id"`
	ProviderPayoutID pgtype.Text `json:"provider_payout_id"`
}

func (q *Queries) ListProcessingPayouts(ctx context.Context, limit int32) ([]ListProcessingPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listProcessingPayouts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProcessingPayoutsRow
	for rows.Next() {
		var i ListProcessingPayoutsRow
		if err := rows.Scan(&i.ID, &i.ProviderPayoutID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsettledCompletedOrders = `-- name: ListUnsettledCompletedOrders :many

SELECT o.id, o.amount, o.updated_at
FROM orders o
JOIN locations l ON l.id = o.location_id
LEFT JOIN partner_payout_orders po ON po.order_id = o.id
WHERE l.partner_id = $1
  AND o.status = 'completed'
  AND o.updated_at >= $2
  AND o.updated_at <  $3
  AND po.order_id IS NULL
ORDER BY o.updated_at ASC
`

type ListUnsettledCompletedOrdersParams struct {
	PartnerID   uuid.UUID `json:"partner_id"`
	UpdatedAt   time.Time `json:"updated_at"`
	UpdatedAt_2 time.Time `json:"updated_at_2"`
}

type ListUnsettledCompletedOrdersRow struct {
	ID        uuid.UUID      `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// Завершённые заказы партнёра за период, ещё не включённые ни в одну выплату
func (q *Queries) ListUnsettledCompletedOrders(ctx context.Context, arg ListUnsettledCompletedOrdersParams) ([]ListUnsettledCompletedOrdersRow, error) {
	rows, err := q.db.Query(ctx, listUnsettledCompletedOrders, arg.PartnerID, arg.UpdatedAt, arg.UpdatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsettledCompletedOrdersRow
	for rows.Next() {
		var i ListUnsettledCompletedOrdersRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingPayoutsForDispatch = `-- name: LockPendingPayoutsForDispatch :many

SELECT id
FROM partner_payouts
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Диспатч: захват pending-выплат с блокировкой
func (q *Queries) LockPendingPayoutsForDispatch(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockPendingPayoutsForDispatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayoutCompleted = `-- name: MarkPayoutCompleted :exec
UPDATE partner_payouts
SET status              = 'completed',
    provider_payout_id  = $2,
    processed_at        = NOW()
WHERE id = $1
`

type MarkPayoutCompletedParams struct {
	ID               uuid.UUID   `json:"id"`
	ProviderPayoutID pgtype.Text `json:"provider_payout_id"`
}

func (q *Queries) MarkPayoutCompleted(ctx context.Context, arg MarkPayoutCompletedParams) error {
	_, err := q.db.Exec(ctx, markPayoutCompleted, arg.ID, arg.ProviderPayoutID)
	return err
}

const markPayoutFailed = `-- name: MarkPayoutFailed :exec
UPDATE partner_payouts
SET status         = 'failed',
    error_message  = $2,
    processed_at   = NOW()
WHERE id = $1
`

type MarkPayoutFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkPayoutFailed(ctx context.Context, arg MarkPayoutFailedParams) error {
	_, err := q.db.Exec(ctx, markPayoutFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markPayoutProcessing = `-- name: MarkPayoutProcessing :exec
UPDATE partner_payouts
SET status = 'processing'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkPayoutProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPayoutProcessing, id)
	return err
}

const resetPayoutToPending = `-- name: ResetPayoutToPending :exec
UPDATE partner_payouts
SET status        = 'pending',
    error_message = NULL,
    processed_at  = NULL
WHERE id = $1 AND status = 'failed'
`

func (q *Queries) ResetPayoutToPending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetPayoutToPending, id)
	return err
}

const setProviderPayoutID = `-- name: SetProviderPayoutID :exec
UPDATE partner_payouts
SET provider_payout_id = $2
WHERE id = $1
`

type SetProviderPayoutIDParams struct {
	ID               uuid.UUID   `json:"id"`
	ProviderPayoutID pgtype.Text `json:"provider_payout_id"`
}

func (q *Queries) SetProviderPayoutID(ctx context.Context, arg SetProviderPayoutIDParams) error {
	_, err := q.db.Exec(ctx, setProviderPayoutID, arg.ID, arg.ProviderPayoutID)
	return err
}

const upsertPayoutDestination = `-- name: UpsertPayoutDestination :one
INSERT INTO partner_payout_destinations (
    partner_id, type, sbp_phone, sbp_bank_id, recipient_name
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (partner_id) DO UPDATE SET
    type            = EXCLUDED.type,
    sbp_phone       = EXCLUDED.sbp_phone,
    sbp_bank_id     = EXCLUDED.sbp_bank_id,
    recipient_name  = EXCLUDED.recipient_name,
    updated_at      = NOW()
RETURNING partner_id, type, sbp_phone, sbp_bank_id, recipient_name, created_at, updated_at
`

type UpsertPayoutDestinationParams struct {
	PartnerID     uuid.UUID   `json:"partner_id"`
	Type          string      `json:"type"`
	SbpPhone      pgtype.Text `json:"sbp_phone"`
	SbpBankID     pgtype.Text `json:"sbp_bank_id"`
	RecipientName pgtype.Text `json:"recipient_name"`
}

func (q *Queries) UpsertPayoutDestination(ctx context.Context, arg UpsertPayoutDestinationParams) (PartnerPayoutDestination, error) {
	row := q.db.QueryRow(ctx, upsertPayoutDestination,
		arg.PartnerID,
		arg.Type,
		arg.SbpPhone,
		arg.SbpBankID,
		arg.RecipientName,
	)
	var i PartnerPayoutDestination
	err := row.Scan(
		&i.PartnerID,
		&i.Type,
		&i.SbpPhone,
		&i.SbpBankID,
		&i.RecipientName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
