// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pins.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLocationPin = `-- name: CreateLocationPin :one
INSERT INTO location_pins (code, name_ru, sort_order)
VALUES ($1, $2, $3)
RETURNING code, name_ru, sort_order, created_at
`

type CreateLocationPinParams struct {
	Code      string `json:"code"`
	NameRu    string `json:"name_ru"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateLocationPin(ctx context.Context, arg CreateLocationPinParams) (LocationPin, error) {
	row := q.db.QueryRow(ctx, createLocationPin, arg.Code, arg.NameRu, arg.SortOrder)
	var i LocationPin
	err := row.Scan(
		&i.Code,
		&i.NameRu,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLocationPin = `-- name: DeleteLocationPin :exec
DELETE FROM location_pins WHERE code = $1
`

func (q *Queries) DeleteLocationPin(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteLocationPin, code)
	return err
}

const deleteLocationSelectedPins = `-- name: DeleteLocationSelectedPins :exec
DELETE FROM location_selected_pins WHERE location_id = $1
`

func (q *Queries) DeleteLocationSelectedPins(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocationSelectedPins, locationID)
	return err
}

const getLocationSelectedPins = `-- name: GetLocationSelectedPins :many
SELECT lp.code, lp.name_ru, lp.sort_order
FROM location_selected_pins lsp
JOIN location_pins lp ON lp.code = lsp.pin_code
WHERE lsp.location_id = $1
ORDER BY lp.sort_order ASC
`

type GetLocationSelectedPinsRow struct {
	Code      string `json:"code"`
	NameRu    string `json:"name_ru"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) GetLocationSelectedPins(ctx context.Context, locationID uuid.UUID) ([]GetLocationSelectedPinsRow, error) {
	rows, err := q.db.Query(ctx, getLocationSelectedPins, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationSelectedPinsRow
	for rows.Next() {
		var i GetLocationSelectedPinsRow
		if err := rows.Scan(&i.Code, &i.NameRu, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocationSelectedPin = `-- name: InsertLocationSelectedPin :exec
INSERT INTO location_selected_pins (location_id, pin_code)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertLocationSelectedPinParams struct {
	LocationID uuid.UUID `json:"location_id"`
	PinCode    string    `json:"pin_code"`
}

func (q *Queries) InsertLocationSelectedPin(ctx context.Context, arg InsertLocationSelectedPinParams) error {
	_, err := q.db.Exec(ctx, insertLocationSelectedPin, arg.LocationID, arg.PinCode)
	return err
}

const listLocationPins = `-- name: ListLocationPins :many
SELECT code, name_ru, sort_order FROM location_pins ORDER BY sort_order ASC
`

type ListLocationPinsRow struct {
	Code      string `json:"code"`
	NameRu    string `json:"name_ru"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListLocationPins(ctx context.Context) ([]ListLocationPinsRow, error) {
	rows, err := q.db.Query(ctx, listLocationPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationPinsRow
	for rows.Next() {
		var i ListLocationPinsRow
		if err := rows.Scan(&i.Code, &i.NameRu, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
