// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (PartnerApplication, error)
	DeleteApplication(ctx context.Context, id uuid.UUID) error
	FindApplicationByID(ctx context.Context, id uuid.UUID) (PartnerApplication, error)
	ListApplications(ctx context.Context) ([]PartnerApplication, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error
}

var _ Querier = (*Queries)(nil)
