// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireOrderCreationLock(ctx context.Context, arg AcquireOrderCreationLockParams) error
	ActivateLocation(ctx context.Context, id uuid.UUID) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CloseLocation(ctx context.Context, id uuid.UUID) error
	// Count active boxes by location ID
	CountActiveBoxesByLocationID(ctx context.Context, locationID uuid.UUID) (int64, error)
	// Count active locations for pagination
	CountActiveLocations(ctx context.Context, categoryCode pgtype.Text) (int64, error)
	CountActiveOrdersByLocationID(ctx context.Context, locationID uuid.UUID) (int64, error)
	CountLocationReviews(ctx context.Context, locationID uuid.UUID) (int64, error)
	CountOrdersByCustomerID(ctx context.Context, arg CountOrdersByCustomerIDParams) (int64, error)
	CountOrdersByPartnerID(ctx context.Context, arg CountOrdersByPartnerIDParams) (int64, error)
	CountPartnerStatsOrders(ctx context.Context, arg CountPartnerStatsOrdersParams) (int64, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (PartnerApplication, error)
	// Create a new box
	CreateBox(ctx context.Context, arg CreateBoxParams) (SurpriseBox, error)
	// Create new customer
	CreateCustomer(ctx context.Context, phone string) (uuid.UUID, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (PaymentEvent, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	// Create a new media file record
	CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error)
	CreatePartnerEmployee(ctx context.Context, arg CreatePartnerEmployeeParams) (PartnerEmployee, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	DeactivateLocation(ctx context.Context, id uuid.UUID) error
	DeleteApplication(ctx context.Context, id uuid.UUID) error
	// Delete a box
	DeleteBox(ctx context.Context, id uuid.UUID) error
	DeleteLocation(ctx context.Context, id uuid.UUID) error
	// Delete media file record
	DeleteMediaFile(ctx context.Context, id uuid.UUID) error
	DeletePartnerEmployee(ctx context.Context, id uuid.UUID) error
	FindActiveOrdersByLocationId(ctx context.Context, locationID uuid.UUID) ([]Order, error)
	FindApplicationByID(ctx context.Context, id uuid.UUID) (PartnerApplication, error)
	// Get a box by ID
	FindBoxByID(ctx context.Context, id uuid.UUID) (SurpriseBox, error)
	FindCategoryByCode(ctx context.Context, code string) (LocationCategory, error)
	// Get customer by ID
	FindCustomerByID(ctx context.Context, id uuid.UUID) (User, error)
	// Get customer by phone
	FindCustomerByPhone(ctx context.Context, phone string) (User, error)
	FindLocationByID(ctx context.Context, id uuid.UUID) (Location, error)
	FindLocationsByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]Location, error)
	// Get media file by ID
	FindMediaFileByID(ctx context.Context, id uuid.UUID) (MediaFile, error)
	FindPartnerByID(ctx context.Context, id uuid.UUID) (Partner, error)
	FindPartnerEmployeeByEmail(ctx context.Context, email string) (PartnerEmployee, error)
	FindPartnerEmployeeByID(ctx context.Context, id uuid.UUID) (PartnerEmployee, error)
	GetActiveOrderByCustomerAndBox(ctx context.Context, arg GetActiveOrderByCustomerAndBoxParams) (Order, error)
	// Get customer profile with stats
	GetCustomerProfile(ctx context.Context, id uuid.UUID) (GetCustomerProfileRow, error)
	// Get location details by ID with category info
	GetLocationDetailsByID(ctx context.Context, id uuid.UUID) (GetLocationDetailsByIDRow, error)
	GetLocationOrderByID(ctx context.Context, arg GetLocationOrderByIDParams) (GetLocationOrderByIDRow, error)
	GetLocationOrderByPickupCode(ctx context.Context, arg GetLocationOrderByPickupCodeParams) (GetLocationOrderByPickupCodeRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderChatProjection(ctx context.Context, id uuid.UUID) (GetOrderChatProjectionRow, error)
	GetOrderDetailsByID(ctx context.Context, id uuid.UUID) (GetOrderDetailsByIDRow, error)
	GetPartnerDashboardFinance(ctx context.Context, partnerID uuid.UUID) (GetPartnerDashboardFinanceRow, error)
	GetPartnerDashboardTodayStats(ctx context.Context, partnerID uuid.UUID) (GetPartnerDashboardTodayStatsRow, error)
	GetPartnerDashboardWeekStats(ctx context.Context, id uuid.UUID) (GetPartnerDashboardWeekStatsRow, error)
	GetPartnerOrderByID(ctx context.Context, arg GetPartnerOrderByIDParams) (GetPartnerOrderByIDRow, error)
	GetPartnerOrderByPickupCode(ctx context.Context, arg GetPartnerOrderByPickupCodeParams) (GetPartnerOrderByPickupCodeRow, error)
	GetPartnerProfile(ctx context.Context, id uuid.UUID) (GetPartnerProfileRow, error)
	GetPartnerStatsStatusBreakdown(ctx context.Context, arg GetPartnerStatsStatusBreakdownParams) ([]GetPartnerStatsStatusBreakdownRow, error)
	GetPartnerStatsSummary(ctx context.Context, arg GetPartnerStatsSummaryParams) (GetPartnerStatsSummaryRow, error)
	GetPartnerStatsTimeline(ctx context.Context, arg GetPartnerStatsTimelineParams) ([]GetPartnerStatsTimelineRow, error)
	GetPartnerStatsTopBoxes(ctx context.Context, arg GetPartnerStatsTopBoxesParams) ([]GetPartnerStatsTopBoxesRow, error)
	GetPartnerStatsTopLocations(ctx context.Context, arg GetPartnerStatsTopLocationsParams) ([]GetPartnerStatsTopLocationsRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error)
	// List active boxes by location ID
	ListActiveBoxesByLocationID(ctx context.Context, locationID uuid.UUID) ([]SurpriseBox, error)
	ListActiveOrdersByLocationID(ctx context.Context, arg ListActiveOrdersByLocationIDParams) ([]ListActiveOrdersByLocationIDRow, error)
	// Заявки на партнёрство
	ListApplications(ctx context.Context) ([]PartnerApplication, error)
	// List boxes by location ID
	ListBoxesByLocationID(ctx context.Context, locationID uuid.UUID) ([]SurpriseBox, error)
	// List boxes by partner ID
	ListBoxesByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]SurpriseBox, error)
	ListEmployeesByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]PartnerEmployee, error)
	ListLocationReviews(ctx context.Context, arg ListLocationReviewsParams) ([]ListLocationReviewsRow, error)
	// Локации партнёров
	ListLocations(ctx context.Context) ([]Location, error)
	// List all media files (paginated)
	ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]MediaFile, error)
	ListOrdersByCustomerID(ctx context.Context, userID uuid.UUID) ([]Order, error)
	ListOrdersByCustomerIDFiltered(ctx context.Context, arg ListOrdersByCustomerIDFilteredParams) ([]ListOrdersByCustomerIDFilteredRow, error)
	ListOrdersByPartnerIDFiltered(ctx context.Context, arg ListOrdersByPartnerIDFilteredParams) ([]ListOrdersByPartnerIDFilteredRow, error)
	// Сотрудники партнёров
	ListPartnerEmployees(ctx context.Context) ([]PartnerEmployee, error)
	ListPartnerStatsOrders(ctx context.Context, arg ListPartnerStatsOrdersParams) ([]ListPartnerStatsOrdersRow, error)
	// Партнёры (юридические лица)
	ListPartners(ctx context.Context) ([]Partner, error)
	MarkOrderPickedUp(ctx context.Context, arg MarkOrderPickedUpParams) (int64, error)
	ReserveBox(ctx context.Context, id uuid.UUID) (int64, error)
	// Location queries for customer app
	// Search locations
	SearchLocations(ctx context.Context, arg SearchLocationsParams) ([]SearchLocationsRow, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error
	// Update an existing box
	UpdateBox(ctx context.Context, arg UpdateBoxParams) (SurpriseBox, error)
	// Update customer profile
	UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (User, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateLocationStatus(ctx context.Context, arg UpdateLocationStatusParams) error
	UpdateLocationWorkingHours(ctx context.Context, arg UpdateLocationWorkingHoursParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePartner(ctx context.Context, arg UpdatePartnerParams) error
	UpdatePartnerEmployee(ctx context.Context, arg UpdatePartnerEmployeeParams) error
	UpdatePartnerEmployeePassword(ctx context.Context, arg UpdatePartnerEmployeePasswordParams) error
	UpdatePartnerStatusByID(ctx context.Context, arg UpdatePartnerStatusByIDParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpsertPartnerLegalInfo(ctx context.Context, arg UpsertPartnerLegalInfoParams) (PartnerLegalInfo, error)
}

var _ Querier = (*Queries)(nil)
