// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLocationReviews = `-- name: CountLocationReviews :one
SELECT COUNT(*)
FROM reviews
WHERE location_id = $1
`

func (q *Queries) CountLocationReviews(ctx context.Context, locationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLocationReviews, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
        order_id,
        user_id,
        location_id,
        rating,
        comment
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, user_id, location_id, rating, comment, created_at, updated_at
`

type CreateReviewParams struct {
	OrderID    uuid.UUID   `json:"order_id"`
	UserID     uuid.UUID   `json:"user_id"`
	LocationID uuid.UUID   `json:"location_id"`
	Rating     int32       `json:"rating"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.OrderID,
		arg.UserID,
		arg.LocationID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.LocationID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationReviews = `-- name: ListLocationReviews :many
SELECT r.id,
    r.rating,
    COALESCE(r.comment, '') AS comment,
    COALESCE(u.name, '') AS user_name,
    r.created_at
FROM reviews r
    JOIN users u ON u.id = r.user_id
WHERE r.location_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLocationReviewsParams struct {
	LocationID uuid.UUID `json:"location_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListLocationReviewsRow struct {
	ID        uuid.UUID `json:"id"`
	Rating    int32     `json:"rating"`
	Comment   string    `json:"comment"`
	UserName  string    `json:"user_name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListLocationReviews(ctx context.Context, arg ListLocationReviewsParams) ([]ListLocationReviewsRow, error) {
	rows, err := q.db.Query(ctx, listLocationReviews, arg.LocationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationReviewsRow
	for rows.Next() {
		var i ListLocationReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.UserName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
