http:
  middlewares:
    api-ratelimit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s

    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          X-Powered-By: ""

    chat-api-rewrite:
      replacePathRegex:
        regex: "^/chat-api(.*)"
        replacement: "/api$1"

    chat-ws-rewrite:
      replacePathRegex:
        regex: "^/chat-ws(.*)"
        replacement: "/ws$1"

  routers:
    api:
      rule: "Host(`fooday.live`) && PathPrefix(`/api/`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: api-service
      priority: 20
      middlewares:
        - api-ratelimit
        - secure-headers

    frontend:
      rule: "Host(`fooday.live`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: frontend-service
      priority: 1

    chat-api:
      rule: "Host(`fooday.live`) && PathPrefix(`/chat-api/`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: chat-service
      priority: 30
      middlewares:
        - chat-api-rewrite
        - api-ratelimit

    portainer:
      rule: "Host(`portainer.fooday.live`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: portainer-service

    chat-ws:
      rule: "Host(`fooday.live`) && PathPrefix(`/chat-ws`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: chat-service
      priority: 25
      middlewares:
        - chat-ws-rewrite

  services:
    portainer-service:
      loadBalancer:
        servers:
          - url: "http://berezhok-portainer:9000"

    api-service:
      loadBalancer:
        servers:
          - url: "http://berezhok-api:8080"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://berezhok-frontend:80"

    chat-service:
      loadBalancer:
        servers:
          - url: "http://berezhok-chat:8090"
